#!/usr/bin/env python3

# Generate shader source to be included at compile time.
#
# Each shader file is emitted as an escaped C string literal (via json.dumps,
# which produces valid C-string escaping for ascii GLSL) so the output compiles
# as plain C as well as C++:
#
#   const GLchar* velocity_VertexShaderSource = "#version 330 core\n...";
#
# Usage (see nob.c for how the build drives this):
#
#   python3 embed_shader.py shaders/velocity.vert shaders/velocity.frag shaders/velocity.h
#
# then compile with shaders/ on the include path, and the C source does:
#
#   #include "velocity.h"

import json
import os
import re


# Courtesy of https://stackoverflow.com/a/3305731/2531987
def sanitize(var_string):
    return re.sub(r"\W|^(?=\d)", "_", var_string)


def emit_C_string(shader_text, shader_name, kind):
    if kind == "vert":
        kind_name = "Vertex"
    elif kind == "frag":
        kind_name = "Fragment"
    else:
        raise NotImplementedError(f'Unknown shader kind "{kind}"')

    name = sanitize(shader_name)
    c_string = json.dumps(shader_text)
    return (
        f"// {kind_name} shader source automatically generated by embed_shader.py\n"
        f"const GLchar* {name}_{kind_name}ShaderSource = {c_string};\n"
    )


def main(argv):
    # Last argv is the target file
    target_file = argv[-1]
    _, ext = os.path.splitext(target_file)
    if ext != ".hpp" and ext != ".h":
        raise OSError("Output file extension must be .h or .hpp")

    out = []
    for shader_file in argv[1:-1]:
        print(f'Processing "{shader_file}"')

        with open(shader_file, "r") as f:
            shader_text = f.read()

        base, shader_ext = os.path.splitext(shader_file)
        _, shader_name = os.path.split(base)

        out.append(emit_C_string(shader_text, shader_name, shader_ext[1:]))
        out.append("\n")

    with open(target_file, "w") as f:
        f.write("".join(out))


if __name__ == "__main__":
    import sys

    main(sys.argv)
