#if 0
mkdir -p bin
if [ ! -f bin/nob ]; then cc -o bin/nob "$0" || exit 1; fi
exec ./bin/nob "$@"
#endif
// Bootstrap: `./nob.c` (or `sh nob.c`). The nob binary + its .old backup live
// in bin/ (gitignored), so running ./nob.c doesn't litter the repo root.
// argv[0] is ./bin/nob, so the Go Rebuild Urself tech rebuilds in place there
// when nob.c changes (NOB_GO_REBUILD_URSELF below).
//
// Targets: build (default), run, clean.

#define NOB_IMPLEMENTATION
#define NOB_STRIP_PREFIX
#include "lib/nob.h"

#define INI_IMPLEMENTATION // header-only inih; this TU (the build tool) emits the impl
#include "lib/ini.h"       // used to parse default-params at build time

#include <string.h>

#define SHADER_DIR "shaders" // holds .vert/.frag sources + generated <name>.h (gitignored)
#define BIN_DIR "bin"
#define DEFAULT_PARAMS_SRC "default-params.ini" // source-of-truth default config
#define DEFAULT_PARAMS_HDR "default_params.h"  // generated token array (gitignored)

static const char *bin_path = BIN_DIR "/goo";

// Each shader has a .vert + .frag embedded into <name>.h by generate_shaders()
static const char *shaders[] = {"copy", "debug", "density", "position", "screen", "trail", "upscale", "velocity"};

static const char *sources[] = {
    "main.c", "shader.c", "buffer.c", "rgfw_impl.c",
    // dropt cli option parser is now a single header (lib/dropt/dropt.h);
    // main.c emits its impl via DROPT_IMPLEMENTATION
    // inih .ini config parser is likewise single-header (lib/ini.h); main.c
    // emits its impl via INI_IMPLEMENTATION
};

static void add_platform_libs(Cmd *cmd) {
#if defined(__APPLE__)
    cmd_append(cmd, "-framework", "Cocoa", "-framework", "CoreVideo", "-framework", "IOKit", "-framework", "OpenGL");
#elif defined(_WIN32)
    cmd_append(cmd, "-lopengl32", "-lgdi32");
#else
    cmd_append(cmd, "-lX11", "-lXrandr", "-lGL", "-lm");
#endif
}

// append src (count bytes) as an escaped C string literal, surrounding quotes included.
// GLSL is ascii so json.dumps' \uXXXX is overkill (and invalid C for <0x20); fixed
// 3-digit octal escapes are valid C and never run greedily into the next char.
static void sb_append_escaped(String_Builder *sb, const char *src, size_t count) {
    da_append(sb, '"');
    for (size_t i = 0; i < count; i++) {
        unsigned char c = (unsigned char)src[i];
        switch (c) {
            case '"':  sb_append_cstr(sb, "\\\""); break;
            case '\\': sb_append_cstr(sb, "\\\\"); break;
            case '\n': sb_append_cstr(sb, "\\n");  break;
            case '\t': sb_append_cstr(sb, "\\t");  break;
            case '\r': break; // drop CR -> matches python text-mode universal newlines
            default:
                if (c >= 0x20 && c < 0x7f) da_append(sb, (char)c);
                else sb_appendf(sb, "\\%03o", c);
        }
    }
    da_append(sb, '"');
}

// emit one shader TU (vert or frag) as `const GLchar* <name>_<Kind>ShaderSource = "...";`
static bool emit_shader(String_Builder *sb, const char *name, const char *kind, const char *path) {
    String_Builder src = {0};
    bool ok = read_entire_file(path, &src);
    if (ok) {
        sb_appendf(sb, "// %s shader source automatically generated by nob.c\n", kind);
        sb_appendf(sb, "const GLchar* %s_%sShaderSource = ", name, kind);
        sb_append_escaped(sb, src.items, src.count);
        sb_append_cstr(sb, ";\n\n");
    }
    sb_free(src);
    return ok;
}

static bool generate_shaders(void) {
    // Generated headers land next to their sources in shaders/ (gitignored there)
    bool result = true;
    String_Builder sb = {0};
    for (size_t i = 0; i < NOB_ARRAY_LEN(shaders); i++) {
        const char *name = shaders[i];
        const char *vert = temp_sprintf("%s/%s.vert", SHADER_DIR, name);
        const char *frag = temp_sprintf("%s/%s.frag", SHADER_DIR, name);
        const char *out  = temp_sprintf("%s/%s.h", SHADER_DIR, name);
        // skip if the generated .h is newer than both its .vert/.frag sources
        const char *ins[] = {vert, frag};
        int needed = needs_rebuild(out, ins, NOB_ARRAY_LEN(ins));
        if (needed < 0) return_defer(false);
        if (!needed) continue;
        nob_log(NOB_INFO, "embedding %s -> %s", name, out);
        sb.count = 0;
        if (!emit_shader(&sb, name, "Vertex", vert))   return_defer(false);
        if (!emit_shader(&sb, name, "Fragment", frag)) return_defer(false);
        if (!write_entire_file(out, sb.items, sb.count)) return_defer(false);
    }
defer:
    sb_free(sb);
    return result;
}

// inih handler: append one `key = value` from default-params as a C string
// literal "--key=value" entry. user is the destination String_Builder for the
// array body; the running count is tracked via a trailing newline-per-entry.
static int default_param_handler(void *user, const char *section, const char *name, const char *value) {
    (void)section; // default-params is flat -- flags have no namespaces
    String_Builder *body = user;
    // values here are our own (numbers / simple tokens); no escaping needed.
    sb_appendf(body, "    \"--%s=%s\",\n", name, value);
    return 1; // inih: nonzero = ok
}

// Parse default-params (the source of truth for default config) and emit
// default_params.h: a DEFAULT_PARAMS[] string array main.c feeds to dropt as its
// first option layer. Parsing here means a malformed file fails the build.
static bool generate_default_params(void) {
    const char *ins[] = {DEFAULT_PARAMS_SRC};
    int needed = needs_rebuild(DEFAULT_PARAMS_HDR, ins, NOB_ARRAY_LEN(ins));
    if (needed < 0) return false;
    if (!needed) return true;
    nob_log(NOB_INFO, "embedding %s -> %s", DEFAULT_PARAMS_SRC, DEFAULT_PARAMS_HDR);

    bool result = true;
    String_Builder body = {0};
    int err = ini_parse(DEFAULT_PARAMS_SRC, default_param_handler, &body);
    if (err < 0) { nob_log(NOB_ERROR, "cannot open %s", DEFAULT_PARAMS_SRC); return_defer(false); }
    if (err > 0) { nob_log(NOB_ERROR, "%s: parse error on line %d", DEFAULT_PARAMS_SRC, err); return_defer(false); }

    String_Builder out = {0};
    sb_appendf(&out, "// generated by nob.c from %s -- do not edit\n", DEFAULT_PARAMS_SRC);
    sb_append_cstr(&out, "static const char *DEFAULT_PARAMS[] = {\n");
    sb_append_buf(&out, body.items, body.count);
    sb_append_cstr(&out, "};\n");
    if (!write_entire_file(DEFAULT_PARAMS_HDR, out.items, out.count)) result = false;
    sb_free(out);
defer:
    sb_free(body);
    return result;
}

static bool build_goo(void) {
    if (!mkdir_if_not_exists(BIN_DIR)) return false;

    // skip the compile if bin/goo is newer than every source + generated header.
    // headers (shaders/<name>.h, *.h) are pulled in via #include, so editing one
    // must trigger a rebuild -- list them as inputs alongside the .c TUs.
    File_Paths inputs = {0};
    for (size_t i = 0; i < NOB_ARRAY_LEN(sources); i++) da_append(&inputs, sources[i]);
    for (size_t i = 0; i < NOB_ARRAY_LEN(shaders); i++)
        da_append(&inputs, temp_sprintf("%s/%s.h", SHADER_DIR, shaders[i]));
    da_append(&inputs, "shader.h");
    da_append(&inputs, "buffer.h");
    da_append(&inputs, "lib/RGFW.h");
    da_append(&inputs, "lib/gl.h");
    da_append(&inputs, "lib/dropt.h");
    da_append(&inputs, "lib/ini.h");
    da_append(&inputs, DEFAULT_PARAMS_HDR); // generated; main.c includes it
    int needed = needs_rebuild(bin_path, inputs.items, inputs.count);
    da_free(inputs);
    if (needed < 0) return false;
    if (!needed) {
        nob_log(NOB_INFO, "%s up to date", bin_path);
        return true;
    }

    Cmd cmd = {0};
    nob_cc(&cmd);
    cmd_append(&cmd, "-O3");
    cmd_append(&cmd, "-Ilib", "-I" SHADER_DIR);
    cmd_append(&cmd, "-o", bin_path);
    for (size_t i = 0; i < NOB_ARRAY_LEN(sources); i++) cmd_append(&cmd, sources[i]);
    add_platform_libs(&cmd);
    return cmd_run(&cmd);
}

static void usage(const char *program) {
    nob_log(NOB_INFO, "usage: %s [build|run|clean|help]", program);
    nob_log(NOB_INFO, "  build  compile to %s", bin_path);
    nob_log(NOB_INFO, "  run    build and run");
    nob_log(NOB_INFO, "  clean  remove %s/ and generated %s/*.h", BIN_DIR, SHADER_DIR);
    nob_log(NOB_INFO, "  help   (default) show this message");
}

int main(int argc, char **argv) {
    NOB_GO_REBUILD_URSELF(argc, argv);

    const char *program = argv[0];
    const char *target = argc > 1 ? argv[1] : "help";

    if (strcmp(target, "help") == 0) {
        usage(program);
        return 0;
    }

    if (strcmp(target, "clean") == 0) {
        // remove the binary dir + the generated shader headers (cmd_run has no
        // shell, so no glob: list each shaders/<name>.h explicitly)
        Cmd cmd = {0};
        cmd_append(&cmd, "rm", "-rf", BIN_DIR);
        for (size_t i = 0; i < NOB_ARRAY_LEN(shaders); i++) {
            cmd_append(&cmd, temp_sprintf("%s/%s.h", SHADER_DIR, shaders[i]));
        }
        cmd_append(&cmd, DEFAULT_PARAMS_HDR); // generated default config tokens
        return cmd_run(&cmd) ? 0 : 1;
    }

    if (strcmp(target, "build") != 0 && strcmp(target, "run") != 0) {
        nob_log(NOB_ERROR, "unknown target: %s", target);
        usage(program);
        return 1;
    }

    if (!generate_shaders()) return 1;
    if (!generate_default_params()) return 1;
    if (!build_goo()) return 1;

    if (strcmp(target, "run") == 0) {
        // forward everything after "run" to goo, e.g. `nob run --help -p 1000`
        Cmd cmd = {0};
        cmd_append(&cmd, bin_path);
        for (int i = 2; i < argc; i++) cmd_append(&cmd, argv[i]);
        return cmd_run(&cmd) ? 0 : 1;
    }

    return 0;
}
