// Window-agnostic simulation core. See sim.h for the front-end contract.
// This translation unit emits the glad / dropt / inih single-header impls, so it
// must be linked into every binary exactly once (and the front-ends must not
// re-emit them).

#include "sim.h"

#include <math.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define DROPT_IMPLEMENTATION // header-only dropt: this is the single TU that emits the impl
#include <dropt.h>           // cli option parser (lib/dropt/)

#define INI_IMPLEMENTATION // header-only inih: this is the single TU that emits the impl
#include <ini.h>           // inih: .ini config parser (lib/ini.h)
#include <limits.h>        // INT_MAX/INT_MIN for parse_int range check
#include <string.h>
#include <strings.h> // strcasecmp

#include "default_params.h" // generated by nob.c from default-params: DEFAULT_PARAMS[]

#define GLAD_GL_IMPLEMENTATION // header-only glad: this is the single TU that emits the impl
#include <gl.h>

#include <cglm/cglm.h>
#include <cglm/noise.h>

// width/height are the INTERNAL render (sim) resolution -- logical points divided
// by render_scale. Everything (physics-independent visual passes, density/trail
// buffers, window_shape) is computed against this, then nearest-upscaled to the
// actual framebuffer (window_width/height). This decouples fill cost from device
// DPI (retina renders at 1x) and gives a single perf/quality knob via render_scale.
int width = 0;
int height = 0;
int window_width = 800; // actual framebuffer size in device px; the upscale target
int window_height = 600;
double render_scale = 0; // internal res = logical points / render_scale (>1 = lower res, faster); --render-scale
// SIM_SCALE fixes the simulation coordinate space at logical/SIM_SCALE px, INDEPENDENT of render_scale.
// This makes render_scale a pure fidelity knob (changing -r never alters the dynamics) and a window
// resize just grows/shrinks the field. Set to the historical default render_scale so the default look
// is byte-for-byte preserved; all sim length constants are interpreted in this space.
const double SIM_SCALE = 2.0;
int sim_width = 0, sim_height = 0; // simulation field size in sim px (logical/SIM_SCALE), set in sim_set_dims
float mouse_scale = 1.0f;          // logical-point -> sim-space scale
float dpi_scale = 1.0f;            // logical-point -> physical-pixel scale (>1 on Retina)
const char *title = "Pixel Goo";
// runtime-tunable via cli (see parse_args). NOTE: the default VALUES live in the
// default-params file (baked in at build, applied first in parse_args), not here.
// flag-backed globals below init to 0 purely as storage -- default-params is the
// single source of truth and overwrites them before the sim starts. (P is the
// exception: it has no default-params entry, so its fallback constant stays.)
bool fullscreen = true;
bool vsync = true;
bool profile = false;              // --profile: glFinish per pass + print ms (disables pipelining)
int max_iterations = 0;            // -N: exit after N PRESENTED frames (0 = unlimited); for benchmarking
int warmup = 0;                    // --warmup: simulate this many frames before presenting (skip the boring ramp)
int fps_cap = 0;                   // --fps: throttle the average fps to this (0 = uncapped)
bool no_keyfocus_steal = false;    // --no-keyfocus-steal: show window w/out grabbing key focus
bool no_border = false;            // --no-border: hide the title bar / border in windowed mode
bool no_mouse = false;             // --no-mouse: disable the mouse repel (park the cursor far off)
bool mouse_debug = false;          // --mouse-debug: draw green dot + trail at cursor
bool corners_debug = false;        // --corners-debug: draw green squares in the window corners
bool exclusions_debug = false;     // --exclusions-debug: tint excluded regions green
bool edge_debug = false;           // --edge-debug: tint the bounding-edge repel bands green
char *dump_path = NULL;            // --dump <prefix>: debug. at exit, write frame + density + trail to <prefix>_*.ppm
const char *dump_params_fmt = NULL; // --dump-params[=FORMAT]: print resolved params and exit (NULL = don't)
char *headless_path = NULL;        // --headless <out>: pipe raw render-res frames to ffmpeg, no window present
FILE *ffmpeg_pipe = NULL;          // popen handle for the headless encode
unsigned char *headless_px = NULL; // reusable readback buffer (width*height*3)
int rng_seed = 0;                  // --seed <N>: fixed RNG seed for reproducible runs (0 = time-based)
double init_warp = 0;              // --init-warp: magnitude of the perlin perturbation on initial positions (0 = pure uniform)
double init_density = 0;           // --density/-d: particles per logical-pixel^2. DEFAULT oracle for P unless -p given.
bool p_given = false;              // whether -p/--particles was passed -- if so it wins over --density
int whichMonitor = 0;

// Textures and framebuffers
GLuint textures[9];
GLuint framebuffers[9];
const PBindex densityBufferIndex = 0;
const PBindex positionBufferIndex1 = 1;
const PBindex positionBufferIndex2 = 2;
const PBindex velocityBufferIndex1 = 3;
const PBindex velocityBufferIndex2 = 4;
const PBindex trailBufferIndex1 = 5;
const PBindex trailBufferIndex2 = 6;
const PBindex renderBufferIndex = 7; // internal colour target, upscaled to the window
const PBindex repelBufferIndex = 8; // force-potential (r) + dispersion (g); single-buffered, stateless

// Physics buffer dims (square-ish texture holding P particles), set in buffer_setup.
int PB_width = 0;
int PB_height = 0;
// PBOs holding position/velocity: filled each frame by glReadPixels(FBO->PBO) and bound
// as vertex attributes for the point passes (faster than vertex texture fetch on this gpu).
GLuint pbo_pos = 0;
GLuint pbo_vel = 0;

Shader screenShader = {.name = "screenShader"};
Shader densityShader = {.name = "densityShader"};
Shader positionShader = {.name = "positionShader"};
Shader velocityShader = {.name = "velocityShader"};
Shader copyShader = {.name = "copyShader"};
Shader trailShader = {.name = "trailShader"};
Shader upscaleShader = {.name = "upscaleShader"};
Shader debugShader = {.name = "debugShader"}; // unified debug overlay: exclusions/edge/mouse (fullscreen fill + markers)
Shader repelShader = {.name = "repelShader"};

// Include shader source files
#include "copy.h"
#include "debug.h"
#include "density.h"
#include "repel.h"
#include "position.h"
#include "screen.h"
#include "trail.h"
#include "upscale.h"
#include "velocity.h"

Buffer trailBuffer = {.name = "Trail Buffer", .textures = textures, .framebuffers = framebuffers, .current = 0, .other = 1};
Buffer positionBuffer = {.name = "Position buffer", .textures = textures, .framebuffers = framebuffers, .current = 0, .other = 1};
Buffer velocityBuffer = {.name = "Velocity buffer", .textures = textures, .framebuffers = framebuffers, .current = 0, .other = 1};
Buffer densityBuffer = {.name = "Density buffer", .textures = textures, .framebuffers = framebuffers, .current = 0, .other = 1};
Buffer screenBuffer = {.name = "Screen buffer", .textures = NULL, .framebuffers = NULL, .current = 0, .other = 1};
// Internal render target: the visual passes draw here at render resolution, then
// upscaleShader nearest-samples it onto screenBuffer (the actual window).
Buffer renderBuffer = {.name = "Render buffer", .textures = textures, .framebuffers = framebuffers, .current = 0, .other = 1};
// Force-potential (r) + dispersion (g) field: single-buffered and stateless -- fully cleared
// and re-splatted (edges + exclusion rects + mouse) from scratch every sim_step, no ping-pong.
Buffer repelBuffer = {.name = "Repel buffer", .textures = textures, .framebuffers = framebuffers, .current = 0, .other = 0};

// Alpha blending of each of the fragments
double densityAlpha = 0; // --dens-alpha: per-particle density deposit
double kernelRadius = 0; // --dens-kernel: density splat radius (sim px)
// Force-field tuning (velocity.frag uniforms). All in sim px / sim units, render_scale-independent.
double densityForce = 0; // --dens-force: density-gradient repel strength
double trailForce = 0;   // --trail-force: trail-gradient attract strength
double repel = 0;        // --repel: overall interaction repel strength (walls + exclusions + mouse)
double reach = 0;        // --reach: density/interaction VDI sampling radius (sim px)
double trailReach = 0;   // --trail-reach: trail sampling radius (sim px)
double antiStick = 0;    // --anti-stick: tiny cardinal drift unsticking motionless particles in repel zones

// The density/trail buffers are heavily downsampled, lerped physics fields -- not
// the rendered image. Scattering every Nth particle into them (with the per-point
// alpha scaled up to compensate) cuts the overdraw/ROP cost without a visible
// change, since the final screen pass still draws all P points. 1 = no subsample.
int densitySubsample = 0; // --dens-sub
int trailSubsample = 0;   // --trail-sub
int dens_every = 0;       // --dens-every: rebuild density field every N frames (reuse between)
int trail_every = 0;      // --trail-every: deposit a rotating 1/N trail subset per frame (decay every frame)

// Screen render: density-weighted cull (--cull), 0 = off .. 1 = maximum thinning.
double cullAmount = 0; // --cull

// Screen colormap auto-exposure. See parse_args help for the knobs.
double renderHeadroom = 0.0;    // --headroom: fixed value (0 = auto-track)
double headroomMargin = 0;      // --headroom-margin: tracked-max multiplier
double headroomAttack = 0;      // --headroom-attack: EMA alpha when density RISES
double headroomRelease = 0;     // --headroom-release: EMA alpha when density FALLS
double renderGamma = 0;         // --gamma: colormap curve (1 = linear/punchy, <1 lifts faint)
bool densityNearest = false;    // --dens-nearest: GL_NEAREST density (chunky pixels) vs default GL_LINEAR
double headroomPct = 0;         // --headroom-pct: track this density percentile, not the max
float headroom_ema = 0.0f;      // running EMA of the density max (the auto headroom)
float *density_readback = NULL; // CPU scratch for reading the density buffer back

// Buffer resolution divisor: the density field is render-res / this.
int densityBufferDownsampling = 0;
int density_width = 0; // computed in buffer_setup once width/height are final
int density_height = 0;
int repelBufferDownsampling = 0; // --repel-downsample: interaction (repel) buffer resolution divisor
int repel_width = 0;  // computed in buffer_setup, like density_width
int repel_height = 0;

double dragCoefficient = 0;   // --drag: quadratic velocity damping coefficient
double ditherCoefficient = 0; // --dither: density-scaled random kick magnitude
double ditherDensityGain = 0; // --dither-gain: gain on the density-scaled dither
double ditherOrtho = 0;       // --dither-ortho: density^2-scaled jitter perpendicular to velocity
bool legacyWedge = false;     // --legacy-wedge: old acos trail-integral heading (drops sign of vy)

// Alpha blending of each of the fragments
double trailIntensity = 0; // --trail-intensity: per-particle trail deposit
double trailTau = 0;       // --trail-tau: trail decay time constant in FRAMES (decays every frame)

// Exp-decay factor per update from a time constant in frames: after `tau` frames the field
// has decayed by 1/e. `every` = frames between decay steps (1 for the per-frame trail), so the
// frame-units tau is invariant to it.
static inline float decay_alpha(double tau_frames, int every) {
    return (float)exp(-(double)every / tau_frames);
}
double trailRadius = 0;          // --trail-kernel: trail splat radius (sim px)
int trailBufferDownsampling = 0; // trail field resolution = render-res / this. --trail-downsample.
double trailVelocityFloor = 0;   // --trail-floor: min velocity for a particle to deposit trail
int trail_width = 0;
int trail_height = 0;

int P = 200000; // --particles

// --exclusions "rect(x,y,w,h);...": exclusion primitives in logical px. Count 0 = no exclusion
// (today's behaviour). Window-only (see is_window_only); wlwp/macwp/x11wp never set these.
float exclusionRects[MAX_EXCLUSION_RECTS][4] = {{0}};
int exclusionRectCount = 0;

// per-pass GPU timing (only populated under --profile)
double pass_ms[8] = {0, 0, 0, 0, 0, 0, 0, 0};
const char *pass_name[8] = {"vel", "pos", "dens", "trail", "scr", "up", "rdbk", "sort"};

double gl_refresh_seconds = 30 * 60; // --gl-refresh: GL-context recreate cadence (default 30m; 0 = off); wallpaper only

// When set (via sim_restore), the next buffer_setup uploads this saved state
// instead of generating a fresh random field. Consumed (cleared) by buffer_setup.
static const SimSnapshot *g_restore = NULL;

// Monotonic seconds; replaces glfwGetTime
double get_time(void) {
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (double)ts.tv_sec + (double)ts.tv_nsec * 1e-9;
}

// Sleep for ms milliseconds (frame pacing). <=0 returns immediately.
void sleep_ms(double ms) {
    if (ms <= 0.0)
        return;
    struct timespec req = {
        .tv_sec = (time_t)(ms / 1000.0),
        .tv_nsec = (long)(fmod(ms, 1000.0) * 1e6),
    };
    nanosleep(&req, NULL);
}

// Uniform random float in [0, 1]; replaces glm::linearRand
static float frand01(void) {
    return (float)rand() / (float)RAND_MAX;
}

// Exponential moving average; seeds on first sample (prev == 0).
double ema(double prev, double sample, double a) {
    return prev == 0.0 ? sample : a * sample + (1.0 - a) * prev;
}

// Ascending float compare, for the auto-headroom percentile (qsort over the tiny density buffer).
static int cmp_float(const void *a, const void *b) {
    float fa = *(const float *)a, fb = *(const float *)b;
    return (fa > fb) - (fa < fb);
}

// Debug dump tooling (--dump). Read a framebuffer back and write it as a PPM so it can be
// eyeballed as an image. glReadPixels is bottom-up, so flip to top-down on write.
void dump_ppm_rgb(const char *path, int w, int h, GLuint fbo) {
    glBindFramebuffer(GL_READ_FRAMEBUFFER, fbo);
    unsigned char *px = (unsigned char *)malloc((size_t)w * h * 3);
    // tightly-packed rgb24: default GL_PACK_ALIGNMENT=4 pads rows when w*3 % 4 != 0
    // (e.g. w=125 -> 375), shearing the readback. force byte packing.
    glPixelStorei(GL_PACK_ALIGNMENT, 1);
    glReadPixels(0, 0, w, h, GL_RGB, GL_UNSIGNED_BYTE, px);
    FILE *f = fopen(path, "wb");
    if (f) {
        fprintf(f, "P6\n%d %d\n255\n", w, h);
        for (int y = h - 1; y >= 0; y--)
            fwrite(px + (size_t)y * w * 3, 1, (size_t)w * 3, f);
        fclose(f);
        fprintf(stdout, "dumped %s\n", path);
    }
    free(px);
}

// Single-channel R32F field -> grayscale PPM, normalised by its own max (printed too, so
// the actual value range is visible -- important once density goes unbounded/additive).
void dump_ppm_scalar(const char *path, int w, int h, GLuint fbo) {
    glBindFramebuffer(GL_READ_FRAMEBUFFER, fbo);
    float *v = (float *)malloc((size_t)w * h * sizeof(float));
    glReadPixels(0, 0, w, h, GL_RED, GL_FLOAT, v);
    float mx = 0.0f;
    for (size_t i = 0; i < (size_t)w * h; i++)
        if (v[i] > mx)
            mx = v[i];
    float norm = mx > 0.0f ? mx : 1.0f;
    unsigned char *px = (unsigned char *)malloc((size_t)w * h);
    for (size_t i = 0; i < (size_t)w * h; i++) {
        float t = v[i] / norm;
        px[i] = (unsigned char)(255.0f * (t < 0.0f ? 0.0f : (t > 1.0f ? 1.0f : t)));
    }
    FILE *f = fopen(path, "wb");
    if (f) {
        fprintf(f, "P5\n%d %d\n255\n", w, h);
        for (int y = h - 1; y >= 0; y--)
            fwrite(px + (size_t)y * w, 1, (size_t)w, f);
        fclose(f);
        fprintf(stdout, "dumped %s (max value %.4f)\n", path, mx);
    }
    free(px);
    free(v);
}

// Tile-coherent draw order. The screen pass binds the goo's scattered points into
// random TBDR tiles, which is the bottleneck; drawing them in screen-tile order via
// an index buffer fixes it. The order is rebuilt by an O(P) counting sort over the
// positions read back into pbo_pos (mapped on the CPU). sort_every controls cadence.
GLuint ibo = 0;
unsigned int *sort_idx = NULL; // P entries: particle indices in tile order
int *sort_key = NULL;          // P entries: per-particle tile bucket (scratch)
int *sort_counts = NULL;       // (nbuckets+1) histogram / prefix-sum scratch
const int sort_tile = 32;      // screen tile size in px (~AGX tile granularity)
int sort_every = 0;            // rebuild the order every N frames (1 = every frame)

// Counting-sort the P particle indices by screen tile, using the positions currently
// in pbo_pos. Uploads the result into ibo. O(P), two linear passes. Out-of-bounds
// positions are clamped (only affects coherence, never correctness).
static void rebuild_sort_order(void) {
    int tilesW = (width + sort_tile - 1) / sort_tile;
    int tilesH = (height + sort_tile - 1) / sort_tile;
    int nb = tilesW * tilesH;
    float inv_tile = 1.0f / (float)sort_tile;

    glBindBuffer(GL_PIXEL_PACK_BUFFER, pbo_pos);
    float *pos = (float *)glMapBuffer(GL_PIXEL_PACK_BUFFER, GL_READ_ONLY);
    if (!pos) {
        glBindBuffer(GL_PIXEL_PACK_BUFFER, 0);
        return;
    }

    for (int i = 0; i <= nb; i++)
        sort_counts[i] = 0;
    for (int i = 0; i < P; i++) {
        int tx = (int)(pos[2 * i] * inv_tile);
        int ty = (int)(pos[2 * i + 1] * inv_tile);
        tx = tx < 0 ? 0 : (tx >= tilesW ? tilesW - 1 : tx);
        ty = ty < 0 ? 0 : (ty >= tilesH ? tilesH - 1 : ty);
        int b = ty * tilesW + tx;
        sort_key[i] = b;
        sort_counts[b + 1]++;
    }
    for (int i = 0; i < nb; i++)
        sort_counts[i + 1] += sort_counts[i];
    for (int i = 0; i < P; i++)
        sort_idx[sort_counts[sort_key[i]]++] = (unsigned int)i;

    glUnmapBuffer(GL_PIXEL_PACK_BUFFER);
    glBindBuffer(GL_PIXEL_PACK_BUFFER, 0);

    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, ibo);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, (size_t)P * sizeof(unsigned int), sort_idx, GL_DYNAMIC_DRAW);
}

// Per-pass GPU timing. LAP(i) drains the pipe (glFinish) and folds the elapsed
// ms since the previous lap into pass_ms[i]. Needs _tp, profile in scope.
#define LAP(i)                                                       \
    do {                                                             \
        if (profile) {                                               \
            glFinish();                                              \
            double _tn = get_time();                                 \
            pass_ms[i] = ema(pass_ms[i], (_tn - _tp) * 1000.0, 0.1); \
            _tp = _tn;                                               \
        }                                                            \
    } while (0)

// dropt int handler that accepts scientific notation ("500", "5e2", "1e6", "2e-1").
// dropt's own dropt_handle_int uses strtol and stops at the 'e'; this uses strtod so
// every int flag takes sci notation too. fractional values round to nearest.
static dropt_error parse_int(dropt_context *ctx, const dropt_option *opt, const char *arg, void *dest) {
    (void)ctx;
    (void)opt;
    if (arg == NULL || arg[0] == '\0')
        return dropt_error_insufficient_arguments;
    char *end;
    double v = strtod(arg, &end);
    if (end == arg || *end != '\0')
        return dropt_error_mismatch;
    // round to nearest, then range-check: sci notation makes it trivial to write a
    // value outside int range (e.g. 1e20), and casting an out-of-range double to int
    // is UB. fail loudly instead.
    double r = v >= 0 ? floor(v + 0.5) : ceil(v - 0.5);
    if (r > (double)INT_MAX)
        return dropt_error_overflow;
    if (r < (double)INT_MIN)
        return dropt_error_underflow;
    *(int *)dest = (int)r;
    return dropt_error_none;
}

// dropt handler for --render-scale: optional val; bare -r enables low-res mode at 2.0.
static dropt_error parse_render_scale(dropt_context *ctx, const dropt_option *opt, const char *arg, void *dest) {
    (void)ctx;
    (void)opt;
    if (arg == NULL) {
        *(double *)dest = 2.0;
        return dropt_error_none;
    }
    return dropt_handle_double(ctx, opt, arg, dest);
}

// dropt handler for --cull: optional val; bare --cull enables culling at 0.8.
static dropt_error parse_cull(dropt_context *ctx, const dropt_option *opt, const char *arg, void *dest) {
    (void)ctx;
    (void)opt;
    if (arg == NULL) {
        *(double *)dest = 0.8;
        return dropt_error_none;
    }
    return dropt_handle_double(ctx, opt, arg, dest);
}

// dropt handler for --seed: optional val; bare --seed picks a random seed and prints it.
static dropt_error parse_seed(dropt_context *ctx, const dropt_option *opt, const char *arg, void *dest) {
    (void)ctx;
    (void)opt;
    if (arg == NULL) {
        int s = (int)(time(NULL) & 0x7fffffff);
        fprintf(stdout, "goo: seed %d\n", s);
        *(int *)dest = s;
        return dropt_error_none;
    }
    return parse_int(ctx, opt, arg, dest);
}

// dropt handler for the particle count: same sci-notation parse as parse_int, but
// also flags that -p was given so it wins over --density.
static dropt_error parse_count(dropt_context *ctx, const dropt_option *opt, const char *arg, void *dest) {
    dropt_error e = parse_int(ctx, opt, arg, dest);
    if (e == dropt_error_none)
        p_given = true;
    return e;
}

// --gl-refresh: a duration with an optional unit suffix s/m/h/d (bare = seconds).
// e.g. "10s", "30m", "1h", "1d", "0". Stored as seconds (double).
static dropt_error parse_duration(dropt_context *ctx, const dropt_option *opt, const char *arg, void *dest) {
    (void)ctx;
    (void)opt;
    if (arg == NULL || arg[0] == '\0')
        return dropt_error_insufficient_arguments;
    char *end;
    double v = strtod(arg, &end);
    if (end == arg || v < 0)
        return dropt_error_mismatch;
    double mult = 1.0;
    if (*end != '\0') {
        switch (*end) {
        case 's': mult = 1.0; break;
        case 'm': mult = 60.0; break;
        case 'h': mult = 3600.0; break;
        case 'd': mult = 86400.0; break;
        default: return dropt_error_mismatch;
        }
        if (end[1] != '\0') // only a single-char unit suffix is allowed
            return dropt_error_mismatch;
    }
    *(double *)dest = v * mult;
    return dropt_error_none;
}

// --density/-d: plain double, but flag that it was explicitly set (for -p/-d exclusion).
static dropt_error parse_density(dropt_context *ctx, const dropt_option *opt, const char *arg, void *dest) {
    (void)ctx;
    (void)opt;
    if (arg == NULL || arg[0] == '\0')
        return dropt_error_insufficient_arguments;
    char *end;
    double v = strtod(arg, &end);
    if (end == arg || *end != '\0')
        return dropt_error_mismatch;
    *(double *)dest = v;
    return dropt_error_none;
}

// --exclusions "rect(x,y,w,h);rect(x,y,w,h);...": exclusion primitives to cut from the sim
// domain, in logical px. Primitive-call syntax: a bare name token followed by a parenthesised,
// comma-separated argument list, ';'-separated calls. Hand-rolled split (no strtok -- same
// manual pointer-walk style as token_flag_name below). Only "rect" (4 numeric args: x,y,w,h)
// is implemented today; any other primitive name, or a malformed call (missing/extra parens,
// wrong arg count, non-numeric field, trailing junk), is a hard reject -- same convention as
// any other flag -- not a silent skip. A primitive count over MAX_EXCLUSION_RECTS is clamped
// with a warning instead, since truncating the tail is a much less surprising failure mode
// than refusing to start.
//
// Storage stays a plain float[4] per rect (no type tag/union) since only one primitive kind
// exists, but the dispatch is keyed off the primitive NAME (not off a fixed field count/
// position), so a second primitive kind later is a new `else if` branch, not a rewrite of the
// call-splitting logic above it.
static dropt_error parse_exclusions(dropt_context *ctx, const dropt_option *opt, const char *arg, void *dest) {
    (void)ctx;
    (void)opt;
    if (arg == NULL || arg[0] == '\0')
        return dropt_error_insufficient_arguments;

    int count = 0;
    const char *call_start = arg;
    while (*call_start != '\0') {
        const char *call_end = strchr(call_start, ';');
        size_t call_len = call_end ? (size_t)(call_end - call_start) : strlen(call_start);
        if (call_len > 0) { // tolerate a trailing/empty ';' segment
            const char *paren = memchr(call_start, '(', call_len);
            if (paren == NULL || call_start[call_len - 1] != ')')
                return dropt_error_mismatch; // no "name(...)" shape at all
            size_t name_len = (size_t)(paren - call_start);
            const char *args_start = paren + 1;
            size_t args_len = call_len - name_len - 2; // minus "name(" and the trailing ")"

            if (name_len == 4 && strncmp(call_start, "rect", 4) == 0) {
                if (count >= MAX_EXCLUSION_RECTS) {
                    fprintf(stderr, "goo: --exclusions: more than %d primitives given, ignoring the rest\n", MAX_EXCLUSION_RECTS);
                    break;
                }
                float v[4];
                const char *field_start = args_start;
                for (int n = 0; n < 4; n++) {
                    char *end;
                    v[n] = strtof(field_start, &end);
                    if (end == field_start || (n < 3 && *end != ','))
                        return dropt_error_mismatch;
                    field_start = (n < 3) ? end + 1 : end;
                }
                if (field_start != args_start + args_len) // trailing junk before the closing ')'
                    return dropt_error_mismatch;
                exclusionRects[count][0] = v[0];
                exclusionRects[count][1] = v[1];
                exclusionRects[count][2] = v[2];
                exclusionRects[count][3] = v[3];
                count++;
            } else {
                return dropt_error_mismatch; // unrecognised primitive name
            }
        }
        call_start += call_len;
        if (*call_start == ';')
            call_start++;
    }
    *(int *)dest = count;
    return dropt_error_none;
}

// --dump-params[=FORMAT]: optional value. Bare flag defaults to "ini". Just records the format
// string; the actual dump + exit happens at the end of parse_args (once all params are resolved).
static dropt_error parse_dump_params(dropt_context *ctx, const dropt_option *opt, const char *arg, void *dest) {
    (void)ctx;
    (void)opt;
    *(const char **)dest = (arg == NULL || arg[0] == '\0') ? "ini" : arg;
    return dropt_error_none;
}

// Config-from-stdin support. `goo -` reads an .ini config from stdin and parses
// it through the SAME dropt options as the cli, so every flag works in either
// place with one validation path. Each `key = value` becomes a `--key=value`
// token; the cli tokens are appended AFTER the config tokens so the cli wins
// (dropt takes the last value). A key present in both warns to stderr.
//
// NOTE: override detection is by long-flag name only. setting a key in config
// and its short alias on the cli (e.g. `particles` in config + `-p` on cli)
// still overrides correctly but is NOT warned about. add a short->long map here
// if that silent case starts mattering.

// tokens (config + borrowed cli) live for the whole process: dropt's string
// handlers (--dump, --headless) keep pointers into them, so we never free.
struct token_list {
    char **items;
    size_t count, cap;
};

static void tl_push(struct token_list *tl, char *tok) {
    if (tl->count == tl->cap) {
        tl->cap = tl->cap ? tl->cap * 2 : 16;
        tl->items = realloc(tl->items, tl->cap * sizeof *tl->items);
        if (!tl->items) {
            fprintf(stderr, "goo: out of memory building config tokens\n");
            exit(EXIT_FAILURE);
        }
    }
    tl->items[tl->count++] = tok;
}

// inih handler: turn `name = value` into a `--name=value` token. section ignored
// (config is flat -- flags have no namespaces). returns 1 (inih: nonzero = ok).
static int config_handler(void *user, const char *section, const char *name, const char *value) {
    (void)section;
    struct token_list *tl = user;
    size_t n = strlen(name), v = strlen(value);
    char *tok = malloc(2 + n + 1 + v + 1); // "--" + name + "=" + value + NUL
    if (!tok) {
        fprintf(stderr, "goo: out of memory parsing config\n");
        exit(EXIT_FAILURE);
    }
    sprintf(tok, "--%s=%s", name, value);
    tl_push(tl, tok);
    return 1;
}

// slurp all of stdin into a malloc'd NUL-terminated buffer.
static char *slurp_stdin(void) {
    size_t cap = 4096, len = 0;
    char *buf = malloc(cap);
    if (!buf) {
        fprintf(stderr, "goo: out of memory reading stdin\n");
        exit(EXIT_FAILURE);
    }
    for (;;) {
        if (len + 1 >= cap) {
            cap *= 2;
            buf = realloc(buf, cap);
            if (!buf) {
                fprintf(stderr, "goo: out of memory reading stdin\n");
                exit(EXIT_FAILURE);
            }
        }
        size_t got = fread(buf + len, 1, cap - 1 - len, stdin);
        len += got;
        if (got == 0)
            break;
    }
    buf[len] = '\0';
    return buf;
}

// the long-flag name a token sets, or NULL if it's not a "--name[=...]" token.
// writes the name (sans "--", sans "=value") into out (size cap); returns out or NULL.
static const char *token_flag_name(const char *tok, char *out, size_t cap) {
    if (tok[0] != '-' || tok[1] != '-')
        return NULL;
    const char *p = tok + 2, *eq = strchr(p, '=');
    size_t len = eq ? (size_t)(eq - p) : strlen(p);
    if (len == 0 || len >= cap)
        return NULL;
    memcpy(out, p, len);
    out[len] = '\0';
    return out;
}

// Flags that only make sense for a real window (geometry, input, file output).
// goo-wlwp (wallpaper) excludes these from its option table AND skips any matching
// baked-in default, so they neither show in --help nor parse on its cli.
static bool is_window_only(const char *name) {
    // NOTE: exclusions/*-debug are NOT here -- they work on the wallpapers via the shared sim core
    // (exclusion physics + the sim_step debug overlay pass), so wlwp/macwp/x11wp expose them too.
    // corners-debug stays window-only: it's drawn by glScissor in the RGFW front-end loops, which
    // the wallpapers don't have.
    static const char *w[] = {
        "monitor", "windowed", "no-border", "width", "height", "fps",
        "corners-debug", "no-keyfocus-steal", "profile", "dump", "headless"};
    for (size_t i = 0; i < sizeof w / sizeof w[0]; i++)
        if (strcmp(name, w[i]) == 0)
            return true;
    return false;
}

// Dump every resolved value param as `key = value`, matching the default-params.ini format, by
// walking the (merged) option table and formatting each entry by its handler. Doubles/ints/bools
// only -- string params (--dump, --headless) and the meta flags (help, dump-params) are skipped,
// as is `particles` (P isn't derived until sim_setup; the resolved oracle is `density`).
static void dump_params_ini(FILE *out, const dropt_option *opts, size_t n) {
    for (size_t i = 0; i < n; i++) {
        const dropt_option *o = &opts[i];
        if (o->long_name == NULL || o->dest == NULL)
            continue; // section headers / valueless entries
        if (strcmp(o->long_name, "help") == 0 || strcmp(o->long_name, "dump-params") == 0)
            continue;
        dropt_option_handler_func h = o->handler;
        if (h == dropt_handle_double || h == parse_density || h == parse_render_scale || h == parse_cull)
            fprintf(out, "%s = %g\n", o->long_name, *(const double *)o->dest);
        else if (h == parse_int || h == parse_seed)
            fprintf(out, "%s = %d\n", o->long_name, *(const int *)o->dest);
        else if (h == dropt_handle_bool)
            fprintf(out, "%s = %d\n", o->long_name, (int)*(const dropt_bool *)o->dest);
        // parse_count (particles), string handlers, etc. -> skipped
    }
}

// Parse command-line options into the runtime globals above. Exits the process
// on --help or on a bad option; returns normally to let the sim start.
void parse_args(int argc, char **argv, bool wlwp, bool macwp) {
    dropt_bool show_help = 0;
#ifdef GOO_VERSION
    dropt_bool show_version = 0; // --version: only compiled in when GOO_VERSION is baked (CI tag builds)
#endif
    dropt_bool windowed = 0;
    dropt_bool no_vsync = 0;
    dropt_bool prof = 0;
#ifdef RGFW_MACOS
    dropt_bool no_focus = 0;
#endif
    dropt_bool dens_near = 0;
    dropt_bool nomouse = 0;
    dropt_bool legacy_wedge = 0;

    // Core options: concern the sim itself, shared by both front-ends.
    dropt_option core_opts[] = {
        {'h', "help", "Show this help and exit.", NULL,
         dropt_handle_bool, &show_help, dropt_attr_halt},
#ifdef GOO_VERSION
        {'\0', "version", "Print the version and exit.", NULL,
         dropt_handle_bool, &show_version, dropt_attr_halt},
#endif

        {'\0', NULL, "\nPARTICLES", NULL, NULL, NULL},
        {'p', "particles", "Number of particles to simulate (plain or scientific notation, e.g. 200000, 1e6).", "N",
         parse_count, &P},
        {'d', "density", "Particles per logical-pixel^2 (sim-area + render-scale independent; default 0.05; excludes -p).", "F",
         parse_density, &init_density},
        {'\0', "init-warp", "Magnitude of the perlin warp on initial positions (0 = pure uniform; default 0.1).", "F",
         dropt_handle_double, &init_warp},
        {'\0', "drag", "Quadratic velocity damping coefficient (higher = more damping; default 0.11).", "F",
         dropt_handle_double, &dragCoefficient},
        {'\0', "dither", "Density-scaled random kick magnitude (default 0.1).", "F",
         dropt_handle_double, &ditherCoefficient},
        {'\0', "dither-gain", "Gain on the density-scaled dither (>1 = more jitter in dense regions; default 6.5).", "F",
         dropt_handle_double, &ditherDensityGain},
        {'\0', "dither-ortho", "Density^2-scaled jitter perpendicular to velocity (default 0).", "F",
         dropt_handle_double, &ditherOrtho},
        {'\0', "dens-force", "Density-gradient repel strength (default 0.04).", "F",
         dropt_handle_double, &densityForce},
        {'\0', "trail-force", "Trail-gradient attract strength (default 0.07).", "F",
         dropt_handle_double, &trailForce},
        {'\0', "repel", "Interaction repel strength: walls + exclusions + mouse (default 0.11).", "F",
         dropt_handle_double, &repel},
        {'\0', "reach", "Density/interaction force sampling radius in sim px (default 20).", "F",
         dropt_handle_double, &reach},
        {'\0', "anti-stick", "Anti-stick drift: tiny per-particle cardinal force freeing motionless particles stuck in repel zones (default 0.009).", "F",
         dropt_handle_double, &antiStick},
        {'\0', "trail-reach", "Trail force sampling radius in sim px (default 30).", "F",
         dropt_handle_double, &trailReach},

        {'\0', NULL, "\nCOLORMAP", NULL, NULL, NULL},
        {'\0', "gamma", "Colormap curve: 1 = linear/punchy, <1 lifts faint regions.", "F",
         dropt_handle_double, &renderGamma},
        {'\0', "cull", "Screen density cull, 0..1 (bare --cull = 0.8; thins denser regions).", "F",
         parse_cull, &cullAmount, dropt_attr_optional_val},
        {'\0', "dens-nearest", "Sample the density field with GL_NEAREST (chunky pixels) instead of GL_LINEAR.", NULL,
         dropt_handle_bool, &dens_near},
        {'\0', "headroom", "Fixed colormap headroom (0 = auto-track the density max).", "F",
         dropt_handle_double, &renderHeadroom},
        {'\0', "headroom-margin", "Auto-headroom: multiplier on the tracked max (>1 darker, <1 brighter).", "F",
         dropt_handle_double, &headroomMargin},
        {'\0', "headroom-attack", "Auto-headroom: EMA speed when density rises / closes (0..1).", "F",
         dropt_handle_double, &headroomAttack},
        {'\0', "headroom-release", "Auto-headroom: EMA speed when density falls / opens (0..1; lower = brightens slower).", "F",
         dropt_handle_double, &headroomRelease},
        {'\0', "headroom-pct", "Auto-headroom: track this density percentile (1 = max; <1 ignores hot-spots).", "F",
         dropt_handle_double, &headroomPct},

        {'\0', NULL, "\nDENSITY / TRAIL", NULL, NULL, NULL},
        {'\0', "dens-alpha", "Per-particle density deposit (default 0.005).", "F",
         dropt_handle_double, &densityAlpha},
        {'\0', "dens-kernel", "Density splat radius in sim px (default 30).", "F",
         dropt_handle_double, &kernelRadius},
        {'\0', "trail-intensity", "Per-particle trail deposit (default 0.06).", "F",
         dropt_handle_double, &trailIntensity},
        {'\0', "trail-tau", "Trail decay time constant in frames (larger = longer-lasting trails; default 6.15).", "F",
         dropt_handle_double, &trailTau},
        {'\0', "trail-kernel", "Trail splat radius in sim px (default 15).", "F",
         dropt_handle_double, &trailRadius},
        {'\0', "trail-floor", "Min particle velocity to deposit trail (default 0.6).", "F",
         dropt_handle_double, &trailVelocityFloor},
        {'\0', "dens-sub", "Density buffer: scatter every Nth particle (higher = less overdraw).", "N",
         parse_int, &densitySubsample},
        {'\0', "dens-downsample", "Density field resolution divisor (render-res / N; higher = coarser/cheaper).", "N",
         parse_int, &densityBufferDownsampling},
        {'\0', "repel-downsample", "Repel (interaction) buffer resolution divisor (render-res / N; higher = coarser edges/exclusions/mouse).", "N",
         parse_int, &repelBufferDownsampling},
        {'\0', "dens-every", "Rebuild the density field every N frames (reuse between; cheaper).", "N",
         parse_int, &dens_every},
        {'\0', "trail-sub", "Trail buffer: scatter every Nth particle (higher = less overdraw).", "N",
         parse_int, &trailSubsample},
        {'\0', "trail-downsample", "Trail field resolution divisor (render-res / N; higher = coarser/cheaper).", "N",
         parse_int, &trailBufferDownsampling},
        {'\0', "trail-every", "Update the trail field every N frames (decay/deposit compensated).", "N",
         parse_int, &trail_every},

        {'\0', NULL, "\nMISC", NULL, NULL, NULL},
        {'r', "render-scale", "Internal render resolution divisor (>1 = lower res, faster, chunkier; bare -r = 2).", "N",
         parse_render_scale, &render_scale, dropt_attr_optional_val},
        {'\0', "seed", "Fixed RNG seed (bare --seed = random but printed for replay; 0 = silent random).", "N",
         parse_seed, &rng_seed, dropt_attr_optional_val},
        {'\0', "sort-every", "Rebuild tile-coherent draw order every N frames (0 = never).", "N",
         parse_int, &sort_every},
        {'\0', "warmup", "Simulate N frames before presenting -- skips the boring startup ramp (both windowed + headless).", "N",
         parse_int, &warmup},
        {'\0', "dump-params", "Print the resolved params (bare = 'ini' format) and exit.", "FORMAT",
         parse_dump_params, &dump_params_fmt, dropt_attr_optional_val},
        {'\0', "no-vsync", "Disable vsync (uncap the frame rate).", NULL,
         dropt_handle_bool, &no_vsync},
        {'\0', "no-mouse", "Disable the mouse repel interaction.", NULL,
         dropt_handle_bool, &nomouse},
        {'\0', "legacy-wedge", "Use the old acos trail-integral heading (drops sign of vy; pre-fix look).", NULL,
         dropt_handle_bool, &legacy_wedge},
        {'N', "iterations", "Exit after N presented frames (0 = unlimited); for benchmarking.", "N",
         parse_int, &max_iterations},

        // Shared by the window AND the wallpapers -- exclusion physics + the debug overlays live
        // in the sim core (sim_step), so every front-end exposes them.
        {'\0', NULL, "\nEXCLUSIONS", NULL, NULL, NULL},
        {'\0', "exclusions", "Exclusion primitives cut from the sim domain: \"rect(x,y,w,h);rect(x,y,w,h);...\" in logical px (max 16; only 'rect' is implemented).", "PRIMITIVES",
         parse_exclusions, &exclusionRectCount},

        {'\0', NULL, "\nDEBUG", NULL, NULL, NULL},
        {'\0', "mouse-debug", "Draw the mouse cursor dot + motion line + repel-radius disc.", NULL,
         dropt_handle_bool, &mouse_debug},
        {'\0', "exclusions-debug", "Blend a green tint over excluded regions (debug: visualise exclusion-primitive placement).", NULL,
         dropt_handle_bool, &exclusions_debug},
        {'\0', "edge-debug", "Blend a green tint over the bounding-edge repel bands (debug: visualise the edge repel regions).", NULL,
         dropt_handle_bool, &edge_debug},
    };

    // Window-only options: geometry, input, file output -- meaningless for a
    // wallpaper. Appended only for the windowed front-end (see is_window_only).
    dropt_option win_opts[] = {
        {'\0', NULL, "\nWINDOW", NULL, NULL, NULL},
        {'m', "monitor", "Index of the monitor to fullscreen onto.", "N",
         parse_int, &whichMonitor},
        {'\0', "windowed", "Run in a window instead of fullscreen.", NULL,
         dropt_handle_bool, &windowed},
        {'\0', "no-border", "Hide the window border/title bar.", NULL,
         dropt_handle_bool, &no_border},
        {'\0', "width", "Window width in pixels (windowed mode).", "N",
         parse_int, &width},
        {'\0', "height", "Window height in pixels (windowed mode).", "N",
         parse_int, &height},
        {'\0', "fps", "Throttle the average frame rate to N fps (0 = uncapped).", "N",
         parse_int, &fps_cap},

        {'\0', NULL, "\nDEBUG (window-only)", NULL, NULL, NULL},
        {'\0', "corners-debug", "Draw green squares in the window corners (debug viewport mapping).", NULL,
         dropt_handle_bool, &corners_debug},
        {'\0', "profile", "Print per-pass GPU times in ms (forces glFinish, disables pipelining).", NULL,
         dropt_handle_bool, &prof},
        // NOTE: macos-only -- samespace cover (Spaces, focus-steal) is meaningless on x11/wayland
#ifdef RGFW_MACOS
        {'\0', "no-keyfocus-steal", "Show the window without stealing keyboard focus (for benchmarking).", NULL,
         dropt_handle_bool, &no_focus},
#endif
        {'\0', "dump", "At exit, write frame + density + trail to <prefix>_*.ppm.", "PREFIX",
         dropt_handle_string, &dump_path},
        {'\0', "headless", "Render -N frames at render-res, piped to ffmpeg (e.g. out.mp4); no window. Needs ffmpeg.", "OUT",
         dropt_handle_string, &headless_path},
    };

    // Wallpaper-only options: only meaningful for the wayland layer-shell front-end.
    dropt_option wlwp_opts[] = {
        {'\0', NULL, "\nWALLPAPER", NULL, NULL, NULL},
        {'\0', "gl-refresh", "Recreate the GL context every <dur> (s/m/h/d; default 30m; 0 = never) to reclaim the freedreno driver leak. See debug/.", "DUR",
         parse_duration, &gl_refresh_seconds},
    };

    // macos-wallpaper-only options: the wayland wallpaper is single-output, so -m
    // (clone to a monitor / all monitors) only makes sense for goo-macwp.
    dropt_option macwp_opts[] = {
        {'\0', NULL, "\nWALLPAPER", NULL, NULL, NULL},
        {'m', "monitor", "Monitor to render the wallpaper on (-1 = clone to all monitors; default 0 = main).", "N",
         parse_int, &whichMonitor},
    };

    // Assemble the final table: core + flavor-specific extras + sentinel.
    size_t n_core = sizeof core_opts / sizeof core_opts[0];
    dropt_option *extra = macwp ? macwp_opts : wlwp ? wlwp_opts
                                                    : win_opts;
    size_t n_extra = macwp ? sizeof macwp_opts / sizeof macwp_opts[0]
                           : wlwp ? sizeof wlwp_opts / sizeof wlwp_opts[0]
                                  : sizeof win_opts / sizeof win_opts[0];
    dropt_option *options = malloc((n_core + n_extra + 1) * sizeof(dropt_option));
    if (!options) {
        fprintf(stderr, "goo: out of memory setting up option parser\n");
        exit(EXIT_FAILURE);
    }
    memcpy(options, core_opts, n_core * sizeof(dropt_option));
    memcpy(options + n_core, extra, n_extra * sizeof(dropt_option));
    memset(options + n_core + n_extra, 0, sizeof(dropt_option)); // sentinel

    const char *prog = macwp ? "goo-macwp" : wlwp ? "goo-wlwp"
                                                  : "goo";

    dropt_context *ctx = dropt_new_context(options);
    if (ctx == NULL) {
        fprintf(stderr, "goo: out of memory setting up option parser\n");
        exit(EXIT_FAILURE);
    }
    dropt_allow_concatenated_arguments(ctx, true);

    // Build the token stream dropt parses. If a bare `-` appears in argv, read an
    // .ini config from stdin first; its tokens go in front so the cli (appended
    // after) overrides on conflict.
    struct token_list cfg = {0};
    bool want_stdin = false;
    bool want_help = false;
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-") == 0)
            want_stdin = true;
        // help wins over everything: honour -h/--help even if other args are bad.
        if (strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0)
            want_help = true;
    }

    // Print help before parsing/stdin so a bad arg -- or a piped `-` we'd block on
    // -- can't suppress it.
    if (want_help) {
        fprintf(stdout, "usage: %s [options]\n", prog);
        dropt_help_params hp;
        dropt_init_help_params(&hp);
        hp.indent = 2;
        hp.description_start_column = 26;
        hp.blank_lines_between_options = false;
        dropt_print_help(stdout, ctx, &hp);
        dropt_free_context(ctx);
        exit(EXIT_SUCCESS);
    }

    // Layer 0: the baked-in defaults from default-params (source of truth, see
    // nob.c). These come first so anything below overrides them silently. For wlwp,
    // skip window-only defaults (monitor/width/height/fps) -- their flags aren't in
    // the table, so dropt would reject the tokens.
    for (size_t i = 0; i < sizeof DEFAULT_PARAMS / sizeof DEFAULT_PARAMS[0]; i++) {
        char key[128];
        if (wlwp && token_flag_name(DEFAULT_PARAMS[i], key, sizeof key) && is_window_only(key))
            continue;
        tl_push(&cfg, (char *)DEFAULT_PARAMS[i]);
    }

    // Layer 1: stdin config (only when `-` is present).
    size_t stdin_start = cfg.count;
    if (want_stdin) {
        char *buf = slurp_stdin();
        int err = ini_parse_string(buf, config_handler, &cfg);
        free(buf);
        if (err < 0) {
            fprintf(stderr, "goo: cannot read config from stdin\n");
            exit(EXIT_FAILURE);
        }
        if (err > 0) {
            fprintf(stderr, "goo: config parse error on stdin line %d\n", err);
            exit(EXIT_FAILURE);
        }
    }
    size_t stdin_end = cfg.count;

    // Layer 2: the cli, appended last so it wins (dropt keeps the last value).
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-") == 0)
            continue; // the stdin sentinel, not a flag
        tl_push(&cfg, argv[i]);
    }

    // Warn for every stdin-config key the cli overrides (long-flag names only;
    // see NOTE). Defaults overridden by stdin/cli are expected and stay silent.
    for (size_t i = stdin_start; i < stdin_end; i++) {
        char ckey[128];
        if (!token_flag_name(cfg.items[i], ckey, sizeof ckey))
            continue;
        for (size_t j = stdin_end; j < cfg.count; j++) {
            char lkey[128];
            if (token_flag_name(cfg.items[j], lkey, sizeof lkey) && strcmp(ckey, lkey) == 0) {
                fprintf(stderr, "goo: config '%s' overridden by cli\n", ckey);
                break;
            }
        }
    }

    dropt_parse(ctx, (int)cfg.count, cfg.items);

    if (dropt_get_error(ctx) != dropt_error_none) {
        fprintf(stderr, "goo: %s\n", dropt_get_error_message(ctx));
        dropt_free_context(ctx);
        exit(EXIT_FAILURE);
    }

#ifdef GOO_VERSION
    if (show_version) {
        fprintf(stdout, "%s\n", GOO_VERSION);
        dropt_free_context(ctx);
        free(options);
        exit(EXIT_SUCCESS);
    }
#endif

    // --dump-params[=FORMAT]: every param is resolved now (and we're still before any window/GL
    // setup, since parse_args runs first). Print + exit. Only 'ini' format so far.
    if (dump_params_fmt != NULL) {
        if (strcmp(dump_params_fmt, "ini") != 0) {
            fprintf(stderr, "goo: unknown --dump-params format '%s' (supported: ini)\n", dump_params_fmt);
            dropt_free_context(ctx);
            free(options);
            exit(EXIT_FAILURE);
        }
        dump_params_ini(stdout, options, n_core + n_extra);
        dropt_free_context(ctx);
        free(options);
        exit(EXIT_SUCCESS);
    }

    dropt_free_context(ctx);
    free(options);

    // Apply the negating switches onto the defaults.
    if (windowed)
        fullscreen = false;
    if (no_vsync)
        vsync = false;
    if (prof)
        profile = true;
#ifdef RGFW_MACOS
    if (no_focus)
        no_keyfocus_steal = true;
#endif
    if (dens_near)
        densityNearest = true;
    if (nomouse)
        no_mouse = true;
    if (legacy_wedge)
        legacyWedge = true;

    // Guard against values that would crash or hang the sim.
    if (P < 1) {
        fprintf(stderr, "goo: --particles must be >= 1\n");
        exit(EXIT_FAILURE);
    }
    // wlwp gets width/height from the layer surface (set after parse), so they're
    // legitimately 0 here -- only the windowed front-end takes them from flags.
    if (!wlwp && (width < 1 || height < 1)) {
        fprintf(stderr, "goo: --width/--height must be >= 1\n");
        exit(EXIT_FAILURE);
    }
    if (render_scale < 1.0) {
        fprintf(stderr, "goo: --render-scale must be >= 1\n");
        exit(EXIT_FAILURE);
    }
    if (densityBufferDownsampling < 1 || trailBufferDownsampling < 1 || repelBufferDownsampling < 1) {
        fprintf(stderr, "goo: --dens-downsample/--trail-downsample/--repel-downsample must be >= 1\n");
        exit(EXIT_FAILURE);
    }
    // Decay time constant feeds exp(-1/tau): tau <= 0 gives alpha 0 (trail wiped every frame),
    // which silently kills the trail dynamics. Reject it.
    if (trailTau <= 0.0) {
        fprintf(stderr, "goo: --trail-tau must be > 0\n");
        exit(EXIT_FAILURE);
    }
    if (densitySubsample < 1 || trailSubsample < 1) {
        fprintf(stderr, "goo: --dens-sub/--trail-sub must be >= 1\n");
        exit(EXIT_FAILURE);
    }
    if (warmup < 0) {
        fprintf(stderr, "goo: --warmup must be >= 0\n");
        exit(EXIT_FAILURE);
    }
}

//=====================================================
//
//   ####  ##   ##    ###    ####    #####  #####
//  ##     ##   ##   ## ##   ##  ##  ##     ##  ##
//   ###   #######  ##   ##  ##  ##  #####  #####
//     ##  ##   ##  #######  ##  ##  ##     ##  ##
//  ####   ##   ##  ##   ##  ####    #####  ##   ##
//
//=====================================================

void shader_setup(void) {
    fprintf(stdout, "Compiling shaders...\n");
    shader_create(&screenShader);
    shader_compile(&screenShader, GL_VERTEX_SHADER, screen_VertexShaderSource);
    shader_compile(&screenShader, GL_FRAGMENT_SHADER, screen_FragmentShaderSource);
    shader_link(&screenShader);

    shader_create(&densityShader);
    shader_compile(&densityShader, GL_VERTEX_SHADER, density_VertexShaderSource);
    shader_compile(&densityShader, GL_FRAGMENT_SHADER, density_FragmentShaderSource);
    shader_link(&densityShader);

    shader_create(&positionShader);
    shader_compile(&positionShader, GL_VERTEX_SHADER, position_VertexShaderSource);
    shader_compile(&positionShader, GL_FRAGMENT_SHADER, position_FragmentShaderSource);
    shader_link(&positionShader);

    shader_create(&velocityShader);
    shader_compile(&velocityShader, GL_VERTEX_SHADER, velocity_VertexShaderSource);
    shader_compile(&velocityShader, GL_FRAGMENT_SHADER, velocity_FragmentShaderSource);
    shader_link(&velocityShader);

    shader_create(&copyShader);
    shader_compile(&copyShader, GL_VERTEX_SHADER, copy_VertexShaderSource);
    shader_compile(&copyShader, GL_FRAGMENT_SHADER, copy_FragmentShaderSource);
    shader_link(&copyShader);

    shader_create(&trailShader);
    shader_compile(&trailShader, GL_VERTEX_SHADER, trail_VertexShaderSource);
    shader_compile(&trailShader, GL_FRAGMENT_SHADER, trail_FragmentShaderSource);
    shader_link(&trailShader);

    shader_create(&upscaleShader);
    shader_compile(&upscaleShader, GL_VERTEX_SHADER, upscale_VertexShaderSource);
    shader_compile(&upscaleShader, GL_FRAGMENT_SHADER, upscale_FragmentShaderSource);
    shader_link(&upscaleShader);

    shader_create(&debugShader);
    shader_compile(&debugShader, GL_VERTEX_SHADER, debug_VertexShaderSource);
    shader_compile(&debugShader, GL_FRAGMENT_SHADER, debug_FragmentShaderSource);
    shader_link(&debugShader);

    shader_create(&repelShader);
    shader_compile(&repelShader, GL_VERTEX_SHADER, repel_VertexShaderSource);
    shader_compile(&repelShader, GL_FRAGMENT_SHADER, repel_FragmentShaderSource);
    shader_link(&repelShader);

    // debugShader (created above) must be linked before updateShaderWindowShape ->
    // push_exclusion_rects (below), which pushes the render-space exclusion rects to it.
    updateShaderWindowShape(width, height);
}

// Push the exclusion-rect list (--exclusions) to every shader that consumes it, each converted
// into that shader's own coordinate space. Called from updateShaderWindowShape so it's
// refreshed on resize too -- both conversions below depend on the current window size.
static void push_exclusion_rects(void) {
    int count = exclusionRectCount > MAX_EXCLUSION_RECTS ? MAX_EXCLUSION_RECTS : exclusionRectCount;
    shader_set_uniform_int(&repelShader, "exclusion_rect_count", count);
    shader_set_uniform_int(&debugShader, "exclusion_rect_count", count);
    for (int i = 0; i < MAX_EXCLUSION_RECTS; i++) {
        char name[32];
        snprintf(name, sizeof name, "exclusion_rects[%d]", i);
        float x = exclusionRects[i][0], y = exclusionRects[i][1], w = exclusionRects[i][2], h = exclusionRects[i][3];

        // Sim-space bounds (repel.frag's wall splat): logical px -> sim px is a plain
        // scale (mouse_scale) -- sim-space y is top-down, same as logical px, no flip needed
        // (matches how mouse_position is scaled in the front-end).
        float sim_rect[4] = {x * mouse_scale, y * mouse_scale, (x + w) * mouse_scale, (y + h) * mouse_scale};
        shader_set_uniform_vec(&repelShader, name, 4, sim_rect);

        // Render-buffer-pixel bounds (debug.frag's overlay): logical px -> render px is a
        // render_scale divide PLUS a y-flip (gl_FragCoord is y-up/bottom-origin; logical px,
        // like the mouse, is top-down) -- mirrors how screen.vert/density.vert project
        // positions into their own render targets.
        float render_rect[4] = {
            x / (float)render_scale,
            (float)height - (y + h) / (float)render_scale,
            (x + w) / (float)render_scale,
            (float)height - y / (float)render_scale,
        };
        shader_set_uniform_vec(&debugShader, name, 4, render_rect);
    }
}

void updateShaderWindowShape(int new_width, int new_height) {
    (void)new_width;
    (void)new_height; // shape comes from the global sim/render dims now

    // window_shape is the SIM space (logical/SIM_SCALE): all physics, density/trail splat, and the
    // screen vertex pass normalise particle positions by it, so the dynamics are render_scale-free.
    float sim_shape[2] = {(float)sim_width, (float)sim_height};
    shader_set_uniform_vec(&screenShader, "window_shape", 2, sim_shape);
    shader_set_uniform_vec(&densityShader, "window_shape", 2, sim_shape);
    shader_set_uniform_vec(&positionShader, "window_shape", 2, sim_shape);
    shader_set_uniform_vec(&velocityShader, "window_shape", 2, sim_shape);
    shader_set_uniform_vec(&trailShader, "window_shape", 2, sim_shape);
    shader_set_uniform_vec(&repelShader, "window_shape", 2, sim_shape);

    // screen.frag samples the density buffer by gl_FragCoord, which is in render-buffer pixels,
    // so it needs the render resolution (width/height), not the sim space.
    float render_shape[2] = {(float)width, (float)height};
    shader_set_uniform_vec(&screenShader, "render_shape", 2, render_shape);

    push_exclusion_rects();

    // The screen buffer is the final upscale target, so it takes the actual window (framebuffer) size.
    screenBuffer.width = window_width;
    screenBuffer.height = window_height;
}

void updateShaderBufferShape(int new_width, int new_height) {
    // buffer_size is dead: the point passes now read positions as PBO attributes
    // instead of mapping gl_VertexID -> texel, so no shader references it anymore.
    (void)new_width;
    (void)new_height;
}

//===================================================
//
//  #####   ##   ##  #####  #####  #####  #####
//  ##  ##  ##   ##  ##     ##     ##     ##  ##
//  #####   ##   ##  #####  #####  #####  #####
//  ##  ##  ##   ##  ##     ##     ##     ##  ##
//  #####    #####   ##     ##     #####  ##   ##
//
//===================================================

void buffer_setup(void) {
    fprintf(stdout, "Setting up buffers...\n");

    // Derived buffer sizes, now that width/height are final (set in the front-end's window setup)
    density_width = width / densityBufferDownsampling + 1;
    density_height = height / densityBufferDownsampling + 1;
    repel_width = width / repelBufferDownsampling + 1;
    repel_height = height / repelBufferDownsampling + 1;
    trail_width = width / trailBufferDownsampling + 1;
    trail_height = height / trailBufferDownsampling + 1;

    // Vertex array. The point passes get their attributes from the PBOs (wired below);
    // the fullscreen-quad passes use gl_VertexID -- so the VAO needs no static buffer.
    GLuint vao;
    glGenVertexArrays(1, &vao);
    glBindVertexArray(vao);

    // Calculate size of the physics buffer
    int PBwidth = ceil(sqrt(P));
    int PBheight = ceil(P / sqrt(P));
    PB_width = PBwidth;
    PB_height = PBheight;
    fprintf(stdout, "%d points\n", P);
    // Initial density (inverse of -d): P over logical screen area, so it's comparable across
    // sim sizes / render scales regardless of whether -p or -d set the count.
    double logical_area = (double)width * height * render_scale * render_scale;
    fprintf(stdout, "Initial density: %.4g particles/logical-px^2\n", logical_area > 0 ? P / logical_area : 0.0);
    fprintf(stdout, "Physics framebuffer shape: %d x %d\n", PBwidth, PBheight);
    updateShaderBufferShape(PBwidth, PBheight);

    // PBOs sized to the full physics buffer (RG = 2 floats/texel). Filled each frame
    // by glReadPixels(FBO->PBO), then reused as GL_ARRAY_BUFFER so the point passes
    // read positions/velocities as streamed attributes instead of vertex texture fetch.
    size_t pb_bytes = (size_t)PBwidth * PBheight * 2 * sizeof(float);
    glGenBuffers(1, &pbo_pos);
    glBindBuffer(GL_PIXEL_PACK_BUFFER, pbo_pos);
    glBufferData(GL_PIXEL_PACK_BUFFER, pb_bytes, NULL, GL_DYNAMIC_COPY);
    glGenBuffers(1, &pbo_vel);
    glBindBuffer(GL_PIXEL_PACK_BUFFER, pbo_vel);
    glBufferData(GL_PIXEL_PACK_BUFFER, pb_bytes, NULL, GL_DYNAMIC_COPY);
    glBindBuffer(GL_PIXEL_PACK_BUFFER, 0);

    // Wire the PBOs as vertex attributes (position = loc 0, velocity = loc 1) on the
    // still-bound VAO, so the point passes stream them instead of vertex texture fetch.
    glBindBuffer(GL_ARRAY_BUFFER, pbo_pos);
    glEnableVertexAttribArray(0);
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 0, 0);
    glBindBuffer(GL_ARRAY_BUFFER, pbo_vel);
    glEnableVertexAttribArray(1);
    glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, 0, 0);
    glBindBuffer(GL_ARRAY_BUFFER, 0);

    // Index buffer + CPU scratch for the tile-coherent draw order (rebuild_sort_order).
    glGenBuffers(1, &ibo);
    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, ibo);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, (size_t)PBwidth * PBheight * sizeof(unsigned int), NULL, GL_DYNAMIC_DRAW);
    {
        int tilesW = (width + sort_tile - 1) / sort_tile;
        int tilesH = (height + sort_tile - 1) / sort_tile;
        sort_idx = (unsigned int *)malloc((size_t)P * sizeof(unsigned int));
        sort_key = (int *)malloc((size_t)P * sizeof(int));
        sort_counts = (int *)malloc(((size_t)tilesW * tilesH + 1) * sizeof(int));
        // Identity order until the first rebuild, so frame 0 still draws every particle.
        for (int i = 0; i < P; i++)
            sort_idx[i] = (unsigned int)i;
        glBufferSubData(GL_ELEMENT_ARRAY_BUFFER, 0, (size_t)P * sizeof(unsigned int), sort_idx);
    }

    // Initalise textures and the associated framebuffers
    glGenTextures(9, textures);
    glGenFramebuffers(9, framebuffers);

    // Texture 0 - Density buffer
    densityBuffer.minmag_filter = densityNearest ? GL_NEAREST : GL_LINEAR; // --dens-nearest for chunky pixels
    densityBuffer.wrap_st = GL_REPEAT;
    densityBuffer.dim = BE_1D;
    buffer_allocate(&densityBuffer, current, densityBufferIndex, density_width, density_height, NULL);
    // Scratch for the auto-headroom: read the (tiny, downsampled) density buffer back to
    // find its max each density update. Sized generously so a resize can't overflow it.
    density_readback = (float *)malloc((size_t)(density_width + 8) * (density_height + 8) * sizeof(float));
    // Seed 0 in auto mode so ema()'s seed-on-zero snaps to the FIRST measured level instead of
    // ramping from a guessed constant (that ramp showed as faint -> bright over the first ~1/attack frames).
    headroom_ema = (float)(renderHeadroom > 0.0 ? renderHeadroom : 0.0);

    // Texture 8 - Repel buffer (r = force potential, g = dispersion). Single-buffered and
    // stateless: fully cleared + re-splatted every sim_step (see the repel pass), so it
    // has no "other" half and never flips. Its own resolution knob (--repel-downsample), decoupled
    // from the density buffer -- this sets the hardness floor for the edge/exclusion/mouse repel.
    repelBuffer.minmag_filter = GL_LINEAR;
    repelBuffer.wrap_st = GL_REPEAT; // matches density/trail: velocity.frag samples it the same way
    repelBuffer.dim = BE_2D;
    buffer_allocate(&repelBuffer, current, repelBufferIndex, repel_width, repel_height, NULL);

    positionBuffer.minmag_filter = GL_NEAREST;
    positionBuffer.dim = BE_2D;
    velocityBuffer.minmag_filter = GL_NEAREST;
    velocityBuffer.dim = BE_2D;

    // Restore path (--gl-refresh): if a snapshot is queued and its dims match, upload
    // the saved particle/trail state instead of generating a fresh field, so the sim
    // continues across a GL-context recreate. NOTE: mismatched dims (only possible if
    // the surface resized between snapshot and setup) fall through to a fresh field.
    bool restoring = g_restore && g_restore->pb_w == PBwidth && g_restore->pb_h == PBheight &&
                     g_restore->tr_w == trail_width && g_restore->tr_h == trail_height;

    // Texture 1 - Position buffer 1
    // --seed makes the initial positions (and so the whole deterministic gpu evolution)
    // reproducible, which is what lets before/after dumps actually be comparable.
    const float *pos_data;
    float *positions = NULL;
    if (restoring) {
        pos_data = g_restore->pos;
    } else {
        srand(rng_seed ? (unsigned int)rng_seed : (unsigned int)time(NULL));
        float margin = (sim_width < sim_height ? sim_width : sim_height) * 0.1f;
        float noise_seed = rng_seed ? (float)rng_seed : (10 * get_time() + frand01());
        fprintf(stdout, "Generating starting positions...\n");
        int N = PBwidth * PBheight * 2;
        positions = (float *)malloc(N * sizeof(float));
        for (int i = 0; i < N; i += 2) {
            // Generate random position in unit range
            vec2 position = {frand01(), frand01()};
            vec3 p0 = {10 * position[0], 10 * position[1], noise_seed};
            vec3 p1 = {10 * position[0], 10 * position[1], noise_seed + 1};
            vec2 noise = {glm_perlin_vec3(p0), glm_perlin_vec3(p1)};
            position[0] += (float)init_warp * fmodf(noise[0], 1.0f);
            position[1] += (float)init_warp * fmodf(noise[1], 1.0f);

            // Cull position to the center of the screen
            position[0] = position[0] * (sim_width - 2 * margin) + margin;
            position[1] = position[1] * (sim_height - 2 * margin) + margin;

            positions[i] = position[0];
            positions[i + 1] = position[1];
        }
        pos_data = positions;
    }

    fprintf(stdout, "Allocating buffers...\n");
    buffer_allocate(&positionBuffer, current, positionBufferIndex1, PBwidth, PBheight, (const char *)pos_data);

    free(positions);

    // Texture 2,3,4 - position buffer 2, velocity buffer 1 and 2. On restore, velocity
    // current gets the saved velocities (else zero); the "other" halves stay zero (the
    // double buffer flips fill them within a frame).
    buffer_allocate(&positionBuffer, other, positionBufferIndex2, PBwidth, PBheight, NULL);
    buffer_allocate(&velocityBuffer, current, velocityBufferIndex1, PBwidth, PBheight,
                    restoring ? (const char *)g_restore->vel : NULL);
    buffer_allocate(&velocityBuffer, other, velocityBufferIndex2, PBwidth, PBheight, NULL);

    // Texture 5,6 - Trail double buffer (current restored from the snapshot if present)
    trailBuffer.minmag_filter = GL_NEAREST;
    trailBuffer.wrap_st = GL_REPEAT;
    trailBuffer.dim = BE_1D;
    buffer_allocate(&trailBuffer, current, trailBufferIndex1, trail_width, trail_height,
                    restoring ? (const char *)g_restore->trail : NULL);
    buffer_allocate(&trailBuffer, other, trailBufferIndex2, trail_width, trail_height, NULL);

    // Texture 7 - internal render target (rgba colour) at render resolution.
    // GL_NEAREST so the upscale to the window stays crisp/pixelated at low res.
    renderBuffer.minmag_filter = GL_NEAREST;
    renderBuffer.wrap_st = GL_CLAMP_TO_EDGE;
    renderBuffer.dim = BE_4D;
    buffer_allocate(&renderBuffer, current, renderBufferIndex, width, height, NULL);

    // The screen buffer is the window itself (the upscale target), in device px.
    screenBuffer.width = window_width;
    screenBuffer.height = window_height;

    // Carry the auto-exposure state across a restore so it doesn't re-ramp, then
    // consume the snapshot (one restore per snapshot).
    if (restoring)
        headroom_ema = g_restore->headroom_ema;
    g_restore = NULL;
}

SimSnapshot *sim_snapshot(void) {
    size_t pv = (size_t)PB_width * PB_height * 2;
    size_t tn = (size_t)trail_width * trail_height;
    SimSnapshot *s = (SimSnapshot *)calloc(1, sizeof *s);
    if (s) {
        s->pos = malloc(pv * sizeof(float));
        s->vel = malloc(pv * sizeof(float));
        s->trail = malloc(tn * sizeof(float));
    }
    if (!s || !s->pos || !s->vel || !s->trail) {
        fprintf(stderr, "goo: out of memory for sim snapshot\n");
        exit(EXIT_FAILURE);
    }
    s->pb_w = PB_width;
    s->pb_h = PB_height;
    s->tr_w = trail_width;
    s->tr_h = trail_height;
    s->headroom_ema = headroom_ema;
    // Read the *current* halves of each double buffer (what sim_step just wrote).
    glBindFramebuffer(GL_READ_FRAMEBUFFER, framebuffers[positionBuffer.current]);
    glReadPixels(0, 0, PB_width, PB_height, GL_RG, GL_FLOAT, s->pos);
    glBindFramebuffer(GL_READ_FRAMEBUFFER, framebuffers[velocityBuffer.current]);
    glReadPixels(0, 0, PB_width, PB_height, GL_RG, GL_FLOAT, s->vel);
    glBindFramebuffer(GL_READ_FRAMEBUFFER, framebuffers[trailBuffer.current]);
    glReadPixels(0, 0, trail_width, trail_height, GL_RED, GL_FLOAT, s->trail);
    glBindFramebuffer(GL_READ_FRAMEBUFFER, 0);
    return s;
}

void sim_restore(const SimSnapshot *s) { g_restore = s; }

void sim_snapshot_free(SimSnapshot *s) {
    if (!s)
        return;
    free(s->pos);
    free(s->vel);
    free(s->trail);
    free(s);
}

void sim_teardown_cpu(void) {
    free(sort_idx);
    sort_idx = NULL;
    free(sort_key);
    sort_key = NULL;
    free(sort_counts);
    sort_counts = NULL;
    free(density_readback);
    density_readback = NULL;
}

//============================================================
//
//   ####  ##  ###    ###      ###    #####  ##
//  ##     ##  ## #  # ##      ## ##   ##  ##  ##
//   ###   ##  ##  ##  ##     ##   ##  #####   ##
//     ##  ##  ##      ##     #######  ##      ##
//  ####   ##  ##      ##     ##   ##  ##      ##
//
//============================================================

void sim_set_dims(int logical_w, int logical_h, int fb_w, int fb_h) {
    // The actual framebuffer (window_width/height) is in device pixels and is only
    // the final upscale target. The sim renders at render resolution (width/height)
    // = logical points / render_scale, so on hidpi/retina it renders at 1x rather
    // than paying the device-pixel fill cost. The mouse comes in logical points, so
    // remember the ratio to scale it into render space.
    window_width = fb_w;
    window_height = fb_h;
    width = (int)((float)logical_w / render_scale + 0.5f);
    height = (int)((float)logical_h / render_scale + 0.5f);
    // Sim space is logical/SIM_SCALE, decoupled from the render resolution above.
    sim_width = (int)((double)logical_w / SIM_SCALE + 0.5);
    sim_height = (int)((double)logical_h / SIM_SCALE + 0.5);
    mouse_scale = (logical_w > 0) ? (float)sim_width / (float)logical_w : 1.0f;
    dpi_scale = (logical_w > 0) ? (float)fb_w / (float)logical_w : 1.0f;
}

// On resize the sim coordinate space (sim_width/height) changes, but the particle
// positions stored in positionBuffer don't -- left as-is they stay clumped in a corner
// of the new (usually larger) field and only slowly diffuse out to fill it. Scale every
// stored position by the size ratio so the field keeps filling the window immediately.
// Readback + reupload on the cpu: resizes are rare, so the cost is irrelevant, and it
// avoids standing up a dedicated scale shader pass. velocities are left unscaled -- they
// re-equilibrate within a few frames and the visible artefact is purely positional.
static void rescale_positions(float kx, float ky) {
    int n = PB_width * PB_height;
    float *p = (float *)malloc((size_t)n * 2 * sizeof(float));
    if (!p)
        return;
    glBindFramebuffer(GL_READ_FRAMEBUFFER, positionBuffer.framebuffers[positionBuffer.current]);
    glReadPixels(0, 0, PB_width, PB_height, GL_RG, GL_FLOAT, p);
    glBindFramebuffer(GL_READ_FRAMEBUFFER, 0);
    for (int i = 0; i < n; i++) {
        p[i * 2] *= kx;
        p[i * 2 + 1] *= ky;
    }
    // keep textures[i] bound to unit i (the convention buffer_allocate sets up).
    glActiveTexture(GL_TEXTURE0 + positionBuffer.current);
    glBindTexture(GL_TEXTURE_2D, positionBuffer.textures[positionBuffer.current]);
    glTexSubImage2D(GL_TEXTURE_2D, 0, 0, 0, PB_width, PB_height, GL_RG, GL_FLOAT, p);
    free(p);
}

void sim_resize(int logical_w, int logical_h, int fb_w, int fb_h) {
    int old_sim_w = sim_width, old_sim_h = sim_height;
    sim_set_dims(logical_w, logical_h, fb_w, fb_h);
    if (old_sim_w > 0 && old_sim_h > 0 && (sim_width != old_sim_w || sim_height != old_sim_h))
        rescale_positions((float)sim_width / (float)old_sim_w, (float)sim_height / (float)old_sim_h);
    glViewport(0, 0, window_width, window_height);
    updateShaderWindowShape(width, height);
    buffer_reallocate(&renderBuffer, current, width, height);
    density_width = width / densityBufferDownsampling + 1;
    density_height = height / densityBufferDownsampling + 1;
    buffer_reallocate(&densityBuffer, current, density_width, density_height);
    // Grow the readback scratch too -- glReadPixels writes density_width*density_height
    // floats into it, so a grow-resize overflows the setup-sized buffer (same class as
    // the sort_counts realloc below). Same generous +8 padding as buffer_setup.
    density_readback = (float *)realloc(density_readback, (size_t)(density_width + 8) * (density_height + 8) * sizeof(float));
    // Repel buffer has its own resolution knob (--repel-downsample); recompute + realloc.
    repel_width = width / repelBufferDownsampling + 1;
    repel_height = height / repelBufferDownsampling + 1;
    buffer_reallocate(&repelBuffer, current, repel_width, repel_height);
    trail_width = width / trailBufferDownsampling + 1;
    trail_height = height / trailBufferDownsampling + 1;
    buffer_reallocate(&trailBuffer, current, trail_width, trail_height);
    buffer_reallocate(&trailBuffer, other, trail_width, trail_height);
    // sort_counts is sized by tile count, which grows with width/height -- resize it too,
    // else rebuild_sort_order writes past the end (sort_idx/sort_key are P-sized, stable).
    {
        int tilesW = (width + sort_tile - 1) / sort_tile;
        int tilesH = (height + sort_tile - 1) / sort_tile;
        sort_counts = (int *)realloc(sort_counts, ((size_t)tilesW * tilesH + 1) * sizeof(int));
    }
}

// Push the static (per-run) uniforms after shaders + buffers exist. The per-frame
// uniforms (mouse, buffer indices, epoch) are set inside sim_step.
static void sim_apply_static_uniforms(void) {
    shader_set_uniform_int(&screenShader, "density_buffer", densityBuffer.current);
    shader_set_uniform_float(&screenShader, "cull_amount", (float)cullAmount);
    shader_set_uniform_float(&screenShader, "render_headroom", (float)renderHeadroom);
    shader_set_uniform_float(&screenShader, "render_gamma", (float)renderGamma);
    shader_set_uniform_int(&densityShader, "density_buffer_downsampling", densityBufferDownsampling);
    // NOTE: the density field accumulates count-per-texel, so its raw value still scales with
    // render_scale (finer buffer = lower peak), and the physics reads it -> -r has a residual
    // effect on the dynamics via field discretisation. Naive texel-area normalisation overcorrects
    // (weaker deposit kills clustering nonlinearly), so it's left alone: -r is a fidelity knob, and
    // the coordinate refactor already makes world size / blob scale / density -r-independent.
    shader_set_uniform_float(&densityShader, "density_alpha", densityAlpha * densitySubsample);
    // kernelRadius is in sim px; the density buffer is at render res, so convert sim->render-px.
    // At the default render_scale == SIM_SCALE the factor is 1 (splat size unchanged).
    shader_set_uniform_float(&densityShader, "kernel_radius", kernelRadius * (float)(SIM_SCALE / render_scale));
    shader_set_uniform_float(&velocityShader, "drag_coefficient", dragCoefficient);
    shader_set_uniform_float(&velocityShader, "dither_coefficient", ditherCoefficient);
    shader_set_uniform_float(&velocityShader, "dither_density_gain", (float)ditherDensityGain);
    shader_set_uniform_float(&velocityShader, "dither_ortho", (float)ditherOrtho);
    shader_set_uniform_int(&velocityShader, "legacy_wedge", legacyWedge ? 1 : 0);
    shader_set_uniform_float(&velocityShader, "density_force", (float)densityForce);
    shader_set_uniform_float(&velocityShader, "trail_force", (float)trailForce);
    shader_set_uniform_float(&velocityShader, "repel_coefficient", (float)repel);
    shader_set_uniform_float(&velocityShader, "reach", (float)reach);
    shader_set_uniform_float(&velocityShader, "anti_stick", (float)antiStick);
    shader_set_uniform_float(&velocityShader, "trail_reach", (float)trailReach);
    shader_set_uniform_int(&velocityShader, "density_buffer", densityBuffer.current);
    // repelBuffer is single-buffered (no ping-pong), so its texture unit never changes.
    shader_set_uniform_int(&velocityShader, "repel_buffer", repelBuffer.current);
    // Trail spread-deposit (--trail-every N): the trail decays EVERY frame (smooth fade,
    // no frozen-field discontinuity), but each frame deposits only a rotating 1/N subset
    // of the trail particles. With the per-point intensity scaled by N, the per-frame
    // deposit total -- and so the field the physics sees -- is unchanged, while the
    // expensive point scatter drops ~N x. Decay alpha stays per-frame (no compounding).
    shader_set_uniform_float(&copyShader, "alpha", decay_alpha(trailTau, 1));
    shader_set_uniform_int(&trailShader, "trail_buffer_downsampling", trailBufferDownsampling);
    shader_set_uniform_float(&trailShader, "trail_intensity", trailIntensity * trailSubsample * trail_every);
    shader_set_uniform_float(&trailShader, "velocity_floor", trailVelocityFloor);
    // sim px -> render-px (trail buffer is at render res); factor 1 at render_scale == SIM_SCALE.
    shader_set_uniform_float(&trailShader, "kernel_radius", trailRadius * (float)(SIM_SCALE / render_scale));
}

void sim_setup(void) {
    // Density is the default oracle for P: unless -p was given explicitly, derive P from the
    // logical (screen) area now that the front-end has set width/height. logical area =
    // width*height*render_scale^2 (width = logical/render_scale), so the count is independent of
    // both sim size and -r. Must run before buffer_setup, which consumes P.
    if (!p_given) {
        double logical_area = (double)width * height * render_scale * render_scale;
        P = (int)(init_density * logical_area + 0.5);
        if (P < 1)
            P = 1;
    }

    shader_setup();
    buffer_setup();
    sim_apply_static_uniforms();
}

// One physics + render frame. Runs the velocity / position / density / trail / screen
// passes into renderBuffer (render resolution). Does NOT present -- the front-end calls
// sim_present (or does its own readback) afterwards.
void sim_step(int epoch_counter, const float mouse_position[2], const float mouse_velocity[2]) {
    double _tp = 0;
    if (profile) {
        glFinish();
        _tp = get_time();
    }

    // Interaction pass: fully clear + re-splat the force-potential (r) / dispersion (g) field
    // from scratch every frame -- bounding-rect edges, exclusion rects (--exclusions), and the
    // mouse. Single-buffered and stateless (no flip), so it's just a plain overwrite. Must run
    // BEFORE the velocity pass, which reads the fully-written result for this frame.
    shader_use(&repelShader);
    shader_set_uniform_vec(&repelShader, "mouse_position", 2, (float *)mouse_position);
    shader_set_uniform_vec(&repelShader, "mouse_velocity", 2, (float *)mouse_velocity);
    shader_set_uniform_vec(&repelShader, "buffer_shape", 2, (float[]){(float)repel_width, (float)repel_height});
    buffer_bind(&repelBuffer, current);
    buffer_update(&repelBuffer);

    // Velocity pass
    shader_use(&velocityShader);
    shader_set_uniform_vec(&velocityShader, "mouse_position", 2, (float *)mouse_position);
    shader_set_uniform_vec(&velocityShader, "mouse_velocity", 2, (float *)mouse_velocity);
    // repel buffer's resolution -- velocity.frag needs it to size the one-texel step of the
    // local-gradient repel (a hard-edged central difference, not the reach-wide VDI).
    shader_set_uniform_vec(&velocityShader, "buffer_shape", 2, (float[]){(float)repel_width, (float)repel_height});
    shader_set_uniform_int(&velocityShader, "position_buffer", positionBuffer.current);
    shader_set_uniform_int(&velocityShader, "velocity_buffer", velocityBuffer.current);
    shader_set_uniform_int(&velocityShader, "trail_buffer", trailBuffer.current);
    shader_set_uniform_int(&velocityShader, "epoch_counter", epoch_counter);
    buffer_bind(&velocityBuffer, other);
    buffer_update(&velocityBuffer);
    buffer_flip(&velocityBuffer);
    LAP(0);

    // Position pass
    shader_use(&positionShader);
    shader_set_uniform_int(&positionShader, "position_buffer", positionBuffer.current);
    shader_set_uniform_int(&positionShader, "velocity_buffer", velocityBuffer.current); // read from updated velocity buffer
    buffer_bind(&positionBuffer, other);
    buffer_update(&positionBuffer);
    buffer_flip(&positionBuffer);
    LAP(1);

    // Copy the fresh position + velocity textures into PBOs (FBO -> GL_PIXEL_PACK_BUFFER,
    // stays on-gpu). Those PBOs are bound as the point passes' vertex attributes, and
    // pbo_pos is also CPU-mapped to build the tile-coherent draw order.
    glBindFramebuffer(GL_READ_FRAMEBUFFER, positionBuffer.framebuffers[positionBuffer.current]);
    glBindBuffer(GL_PIXEL_PACK_BUFFER, pbo_pos);
    glReadPixels(0, 0, PB_width, PB_height, GL_RG, GL_FLOAT, 0);
    glBindFramebuffer(GL_READ_FRAMEBUFFER, velocityBuffer.framebuffers[velocityBuffer.current]);
    glBindBuffer(GL_PIXEL_PACK_BUFFER, pbo_vel);
    glReadPixels(0, 0, PB_width, PB_height, GL_RG, GL_FLOAT, 0);
    glBindBuffer(GL_PIXEL_PACK_BUFFER, 0);
    glBindFramebuffer(GL_READ_FRAMEBUFFER, 0);
    LAP(6);

    // Rebuild the tile-coherent draw order from the freshly read-back positions.
    if (sort_every > 0 && epoch_counter % sort_every == 0) {
        double s0 = get_time();
        rebuild_sort_order();
        pass_ms[7] = ema(pass_ms[7], (get_time() - s0) * 1000.0, 0.1);
    }

    // Density buffer pass. Amortised: the density field is a slow-moving snapshot,
    // and the buffer isn't flipped, so on skipped frames it just keeps the last
    // rebuild (1..N-1 frame stale -- negligible to the velocity integral that reads
    // it). buffer_bind clears, so skip the whole block (not just the draw).
    if (dens_every <= 1 || epoch_counter % dens_every == 0) {
        shader_use(&densityShader);
        shader_set_uniform_int(&densityShader, "density_buffer_downsampling", densityBufferDownsampling);
        buffer_bind(&densityBuffer, current);
        glBlendFunc(GL_ONE, GL_ONE); // additive density accumulation (unbounded)
        buffer_update_n(&densityBuffer, P / densitySubsample);
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA); // restore the global blend

        // Auto-headroom: read the fresh (tiny) density field back, take a high
        // percentile (robust to outlier hot-spots, unlike the raw max), and EMA it --
        // the envelope follower that sets the colormap's makeup gain.
        if (renderHeadroom <= 0.0) {
            glBindFramebuffer(GL_READ_FRAMEBUFFER, framebuffers[densityBuffer.current]);
            glReadPixels(0, 0, density_width, density_height, GL_RED, GL_FLOAT, density_readback);
            glBindFramebuffer(GL_READ_FRAMEBUFFER, 0);
            int n = density_width * density_height;
            qsort(density_readback, n, sizeof(float), cmp_float);
            int k = (int)(headroomPct * (n - 1));
            if (k < 0)
                k = 0;
            else if (k >= n)
                k = n - 1;
            float level = density_readback[k];
            float target = level * (float)headroomMargin;
            // Asymmetric follower: rising target (scene getting denser) closes fast to avoid
            // clipping; falling target (opening up) brightens slowly so it doesn't pop.
            double a = (headroom_ema > 0.0f && target < headroom_ema) ? headroomRelease : headroomAttack;
            headroom_ema = (float)ema(headroom_ema, target, a);
        }
    }
    LAP(2);

    // Trail buffer. Decay every frame (smooth), but deposit only a rotating 1/N
    // subset of the trail particles (--trail-every N), cycling the contiguous block
    // by frame. Particle ids aren't spatially sorted, so each block is a fair random
    // subset; over N frames all contribute. No frozen field -> no discontinuity.
    buffer_bind(&trailBuffer, other);

    shader_use(&copyShader); // First pass (decay the previous trail, every frame)
    shader_set_uniform_float(&copyShader, "alpha", decay_alpha(trailTau, 1));
    shader_set_uniform_int(&copyShader, "source_buffer", trailBuffer.current);
    buffer_update(&trailBuffer);

    shader_use(&trailShader); // Second pass (deposit this frame's rotating subset)
    int trail_total = P / trailSubsample;
    int trail_block = trail_every <= 1 ? trail_total : trail_total / trail_every;
    int trail_start = trail_every <= 1 ? 0 : (epoch_counter % trail_every) * trail_block;
    glDrawArrays(GL_POINTS, trail_start, trail_block);
    buffer_flip(&trailBuffer);
    LAP(3);

    // Screen rendering pass -> internal render target (render resolution)
    buffer_bind(&renderBuffer, current);

    shader_use(&screenShader);
    // Headroom: auto-tracked envelope (renderHeadroom == 0) or the fixed override.
    shader_set_uniform_float(&screenShader, "render_headroom",
                             renderHeadroom > 0.0 ? (float)renderHeadroom : headroom_ema);
    // Draw in tile-coherent order via the index buffer (ibo stays bound in the VAO).
    glDrawElements(GL_POINTS, P, GL_UNSIGNED_INT, 0);

    // Debug overlay: composite flat translucent-green fills into the render target (so they show
    // up in --dump/--headless which read renderBuffer, and regardless of particle density). Gated
    // on the C-side flags -> a normal run pays nothing. renderBuffer is still bound and blend is on
    // (SRC_ALPHA over). Fullscreen quad via gl_VertexID; the bound VAO needs no attributes.
    //  - exclusions_debug: fill each exclusion rect (rects live on the shader from push_exclusion_rects).
    //  - mouse_debug: fill the mouse repel-interaction disc. Radius is the same speed-scaled clamp the
    //    physics uses (repel.frag: clamp(speed*3, 30, 75) sim px -- constants mirrored here for the
    //    viz). sim px -> render px is * SIM_SCALE/render_scale; sim y is top-origin, gl_FragCoord is
    //    bottom-origin, so y flips. A parked mouse sits far off-screen, so its disc covers nothing.
    //  - edge_debug: fill the bounding-edge repel bands (render_shape lets the shader size them).
    //  - mouse_debug also draws the opaque cursor dot + a motion line from last frame's cursor
    //    position (mouse_prev = current - per-frame velocity) to the current one.
    if (exclusions_debug || mouse_debug || edge_debug) {
        shader_use(&debugShader);
        shader_set_uniform_int(&debugShader, "draw_exclusions", exclusions_debug ? 1 : 0);
        shader_set_uniform_int(&debugShader, "draw_mouse", mouse_debug ? 1 : 0);
        shader_set_uniform_int(&debugShader, "draw_edges", edge_debug ? 1 : 0);
        shader_set_uniform_vec(&debugShader, "render_shape", 2, (float[]){(float)width, (float)height});
        // repel buffer's own resolution -- lets the overlay snap to that (downsampled) texel
        // grid, so it shows the ACTUAL coarse field the physics samples, not the ideal shape.
        shader_set_uniform_vec(&debugShader, "buffer_shape", 2, (float[]){(float)repel_width, (float)repel_height});
        float mspeed = sqrtf(mouse_velocity[0] * mouse_velocity[0] + mouse_velocity[1] * mouse_velocity[1]);
        // ease-out radius, mirrors repel.frag/velocity.frag: fast rise at low speed, plateau at max.
        float mt = fminf(mspeed / 20.0f, 1.0f);
        float mrad_sim = 30.0f + (75.0f - 30.0f) * (1.0f - (1.0f - mt) * (1.0f - mt));
        float k = (float)(SIM_SCALE / render_scale);
        shader_set_uniform_vec(&debugShader, "mouse_center", 2,
                               (float[]){mouse_position[0] * k, (float)height - mouse_position[1] * k});
        shader_set_uniform_vec(&debugShader, "mouse_prev", 2,
                               (float[]){(mouse_position[0] - mouse_velocity[0]) * k,
                                         (float)height - (mouse_position[1] - mouse_velocity[1]) * k});
        shader_set_uniform_float(&debugShader, "mouse_radius", mrad_sim * k);
        glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
    }
    LAP(4);
}

void sim_present(void) {
    // Upscale pass: nearest-sample the render target onto the window. Blending
    // is off -- the render target already holds particles composited over black,
    // so this is a straight opaque blit (chunky when render_scale > 1).
    buffer_bind(&screenBuffer, screen);
    glDisable(GL_BLEND);
    shader_use(&upscaleShader);
    shader_set_uniform_int(&upscaleShader, "source_buffer", renderBuffer.current);
    buffer_update(&screenBuffer);
    glEnable(GL_BLEND);
}
